### ISSUE TITLE
Missing "official" hooks (useState, useSelector, etc) sandbox based on standartd

### ISSUE THREAD

**Issue by bfunc** [welldone-software/why-did-you-render#101]
Missing "official" hooks (useState, useSelector, etc) sandbox based on standard ReactCreateApp.
Up-to-date example with Redux (Redux-Toolkit) will be nice too

**Comment by vzaidman** [comment]
ok adding this:
https://codesandbox.io/s/why-did-you-render-sandbox-with-hooks-pyi14
