### ISSUE TITLE
Breaks Fast Refresh in React Native

### ISSUE THREAD

**Issue by JohannesKlauss** [welldone-software/why-did-you-render#105]
Using this package at `4.0.8` with React Native `0.62.2` breaks the Fast Refresh functionality.

As soon as I monkey patch React, Fast Refresh doesn't update the views anymore.

**Comment by JohannesKlauss** [comment]
It seems like this is only happening for components that are either wrapped in `React.memo(...)` and the `trackAllPureComponents` option enabled or that have the `.whyDidYouRender` flag set. So basically every patched component doesn't Fast Refresh.

**Comment by vzaidman** [comment]
Hey!
I've never worked with React Native so I'm open to contributions here, but can't really help.

**Comment by JohannesKlauss** [comment]
I'll have a look into it, but don't really know how the fast refresh works. So no guarantee. If somebody else can have a gander, I'd be glad.

**Comment by vzaidman** [comment]
try following the updated installation guide:
https://github.com/welldone-software/why-did-you-render#installation

re-open if thre's still a problem

**Comment by mariotsi** [comment]
Hello, the link is dead and is also happening to me.

wdyr: 5.0.0
React : 16.14.0

wdyr config 
```
trackAllPureComponents: true,
collapseGroups: true
exclude: [...omit...]
```

As soon as I disable the plugin fast-refresh is working again
