### ISSUE TITLE
Simple render logger?

### ISSUE THREAD

**Issue by OnkelTem** [welldone-software/why-did-you-render#108]
Hi Vitali!

I really like **WhyDidYouRender** and want to thank you one more time, от души!

How difficult it would be to create a logger for printing component names being rendered? Without any options (except for on/off), just simple names printing. In my understanding it's just a minor part of WDYR.

Currently we have to leave `console.log("ComponentName render")` or like in every component and optionally wrap it into `if (process.env.NODE_ENV === "development") {...}`-s. But going WYDR way, we could have just a single initialization call in the `index.js` and then get logging enabled for every component.

I think such a tool would be very helpful.

P.S. Let's imagine what it could have looked like:

```js
if (process.env.NODE_ENV === "development") {
  const renderLogger = require("@welldone-software/render-logger");
  renderLogger(React, {
    enabled: true
  });
}
```

**Comment by vzaidman** [comment]
Hey!
I'm glad you like the library!

see the answer here:
https://github.com/welldone-software/why-did-you-render/issues/76#issuecomment-567442602

**Comment by OnkelTem** [comment]
@vzaidman that's not precisely what I mean. 

I don't mean ANY comparison shallow or not, so it should be really cheap. **WDYR** _somehow_ knows about the whole components tree, and also knows when a component gets rendered. So why not log the fact itself?

As I said currently we have to add in each and every component this minimal code:

```js
  process.env.NODE_ENV === "development" && console.log("MyComponent render");
```

But there's `no-console` ESLint constraint which is usually enabled, and thus we have to create an utility function:

```js
// logger.js
export function renderLogger(str) {
  // eslint-disable-next-line no-console
  process.env.NODE_ENV === "development" && console.log(str);
}
```

and then import it in every component:

```js
// MyComponent.js

  import renderLogger from "what/ever/path/logger";

  // ...
  renderLogger("MyComponent");
  // ...
```

**Comment by vzaidman** [comment]
Sorry, I still don't understand.
the logger function can be changed using options:
https://github.com/welldone-software/why-did-you-render/blob/master/src/normalizeOptions.js

**Comment by OnkelTem** [comment]
I don't want to **replace** WYDR with my logger, I need **two** of them: 

* the default one, which tracks extra renders - what WYDR is created for.
* and another one, of which I'm talking about in this thread and using which I want to print console message for each and every render, unconditionally, as it is. A mere `console.log('Darn, I'm begin rendered again')` thing, but which is control centralized. 

Does it make any clearer?

**Comment by OnkelTem** [comment]
Do you use Discord, Vitali? Could we just catch up there for a moment?

**Comment by vzaidman** [comment]
you can do it like this:
```
SomeSpecificComponent.whyDidYouRender = {
  logOnDifferentValues: true,
}
```
or like this:
```
if (process.env.NODE_ENV === 'development') {
  const whyDidYouRender = require('@welldone-software/why-did-you-render');
  whyDidYouRender(React, {
    logOnDifferentValues: true
  });
}
```

**Comment by OnkelTem** [comment]
Are they gonna be rendered for the same values also?

**Comment by vzaidman** [comment]
yes

**Comment by OnkelTem** [comment]
Thanks! Let me try. If/when I succeed I'll come up with an example sandbox and a snippet.

**Comment by OnkelTem** [comment]
Sorry for the delay.

### Logging 
First, enable logging:
https://codesandbox.io/s/wdyr-simple-logger-1-p4yl3?file=/src/App.js
Initialization code:
```js
if (process.env.NODE_ENV === 'development') {
  const whyDidYouRender = require('@welldone-software/why-did-you-render');
  whyDidYouRender(React, {
    include: [/.*/],
    notifier: ({displayName}) => {
      console.log(`%cWDYR: ${displayName} render`, 'color: red')
    }
  });
}
```
See the red text with `"WDYR: "` prefix - it comes from WDYR.

As you may notice, I didn't use `logOnDifferentValues: true` because it actually does nothing, at least in my sandbox. 
Unfortunately it **doesn't log normal/first renders** - what I wanted in the first place.
Also I couldn't make App component render to be reported.

### Logging + Re-render watchdog
And here is another sandbox, where I use two copies of WDYR: one - for logging and another one - as usual.
https://codesandbox.io/s/wdyr-simple-logger-2-wmpvw?file=/src/App.js

Hence - two initializers:
```js
if (process.env.NODE_ENV === 'development') {
  const whyDidYouRender1 = require('@welldone-software/why-did-you-render');
  whyDidYouRender1(React, {
    include: [/.*/],
    notifier: ({Component, displayName, prevProps, prevState, nextProps, nextState, reason, options}) => {
      console.log(`%cWDYR: ${displayName} render`, 'color: red')
    }
  });
  const whyDidYouRender2 = require('@welldone-software/why-did-you-render');
  whyDidYouRender2(React, {
    trackAllPureComponents: true,
  });
}
```

That's said, so is there a way to log EVERYTHING? :)

**Comment by vzaidman** [comment]
did you try

```
  whyDidYouRender1(React, {
    logOnDifferentValues: true,
    include: [/.*/],
    notifier: ({Component, displayName, prevProps, prevState, nextProps, nextState, reason, options}) => {
      console.log(`%cWDYR: ${displayName} render`, 'color: red')
    }
  });
```

**Comment by OnkelTem** [comment]
Yep. 
I said it doesn't make any change in my sandbox. Here is a demo:
https://codesandbox.io/s/wdyr-simple-logger-11-3gxln?file=/src/index.js

**Comment by vzaidman** [comment]
hey!

take a look at this fixed version:
https://codesandbox.io/s/wdyr-simple-logger-11-fix-p3ilj

I updated the readme yesterday to eliminate these edge cases:
https://github.com/welldone-software/why-did-you-render#installation

the difference is that wdyr should be applies before elements are created, including App.

**Comment by OnkelTem** [comment]
Yay! We did it :) 

Thank you very much, Vitali. 
I should admint I like the way how things work even better than I wanted. I mean not printing the initial render event, it would have been overloading the console.

Also I liked the idea with separate file for WDYR init stuff.

This is how my current implementation looks like in a real project:

```ts
if (process.env.NODE_ENV === 'development') {
  if (process.env.REACT_APP_RENDER_LOGGER) {
    const renderCounter = new Map();
    const whyDidYouRender1 = require('@welldone-software/why-did-you-render');
    whyDidYouRender1(React, {
      include: [/.*/],
      exclude: [
        // Material UI stuff
        /^(ButtonBase|TransitionGroup|Table(Head|Body|Row|Cell)|WithStyles\((ForwardRef|WithStyles).*|(Touch)?Ripple|Paper|Card|CardActions|CardContent|ListItem(Icon|Text)?|Typography|SvgIcon|Grid|Divider|Box|Slider)$/,
        // Navi stuff
        /^(View)$/,
        // Our stuff
      ],
      notifier: ({Component, displayName, prevProps, prevState, nextProps, nextState, reason, options}) => {
        const name = displayName && displayName !== "" ? displayName : "\<Noname\>";
        let c = renderCounter.get(name) || 1;
        const r =
          (reason.propsDifferences !== false ? 'P' : '-') +
          (reason.stateDifferences !== false ? 'S' : '-') +
          (reason.hookDifferences !== false ? 'H' : '-') +
          (reason.ownerDifferences !== false ? 'O' : '-');
        log.a(`WDYR: ${name} (${c++}) [${r}]`);
        renderCounter.set(name, c);
      }
    });
  }
  const whyDidYouRender2 = require('@welldone-software/why-did-you-render');
  whyDidYouRender2(React, {
    onlyLogs: false,
    trackAllPureComponents: true,
    trackExtraHooks: [
      [require("react-redux/lib"), "useSelector"],
    ],
  });
}

```

**Comment by vzaidman** [comment]
Great!
I'm glad it works for you!

**Comment by OnkelTem** [comment]
Yeah, thanks for the help Vitali.

Please consider adding this feature anyway: an option to invoke notifier on all renders, not only on re-renders. It can be a mere boolean flag, e.g. `logEverything: {true|false} false`.
