### ISSUE TITLE
[Preact] Cannot read property 'ReactCurrentOwner' of undefined

### ISSUE THREAD

**Issue by infelipe** [welldone-software/why-did-you-render#109]
Have been trying to setup WDYR with my **Preact** project and it didn't work and I don't know the reason why. Followed every step in the README and it didn't work. I think the problem is in the new version since reverting to v4.0.8 (same version used in another Preact project) fixed it for me. I know it is supposed to work with React, but Preact has great compatibility with almost everything (including WDYR since a previous version worked just fine).

How to replicate:

- `npx create-react-app wdyr-error`
-  Open package.json
- Replace react with `"react": "github:preact-compat/react#1.0.0"`
- Replace react-dom with `"react-dom": "github:preact-compat/react-dom#1.0.0"`
- Setup WDYR
- Delete node_modules and your lockfile, then `npm i` again
- `npm run start`

If needed, I can also create a repo showing the error.

Thank you.

**Comment by vzaidman** [comment]
If you (or anybody reading this) want some guidance on how to fix it, you are welcome to consult with me :)

I never worked with Preact and the chances I get to it are very low.

**Comment by infelipe** [comment]
I've never contributed before, but I can take a look and give it a shot, sure. How can we keep in touch and talk about the fix? Also, thank you for the opportunity

**Comment by vzaidman** [comment]
@infelipe i actually tried to fix it now.
please check if it works for you in version
4.1.3-alpha.0

**Comment by vzaidman** [comment]
@infelipe please take a look at version 4.1.3-alpha.0

**Comment by infelipe** [comment]
Sorry for the late reply, @vzaidman. 
Tested it and it is working well - for my case, at least. I understand that WDYR is not supposed to be 100% compatible with Preact.
Thank you.

**Comment by vzaidman** [comment]
ok I released
https://github.com/welldone-software/why-did-you-render/releases/tag/v4.1.3
with the fix
