### ISSUE TITLE
Memo propsAreEqual is good practice to use?

### ISSUE THREAD

**Issue by andrewvarga** [welldone-software/why-did-you-render#110]
First of all, really useful, nice library! Already helped a lot to optimize components.

There is one warning I'm having trouble with:
`Re-rendered because of prop changes`

I'm getting this in a component which gets props injected by another component that I have no control over (managed by an npm library "react-color"). Some of these props are eg. an rgb object, which is a simple object containing "r", "g", "b" keys and even the value is the same, the object itself seems to be recreated by the component that injects these values.

I tried to fix this by adding a second parameter to my memo call:
```
const MyComponent = memo(props => {
  return (<div>...<div>)
}, (prevProps, nextProps) => {
// deep compare prevProps, nextProps
})
```

This seems to remove the warning from "why-did-you-render" but I want to confirm if this is a good solution in this case? Thank you

**Comment by vzaidman** [comment]
can you link the before props and after props?

**Comment by vzaidman** [comment]
and how this component is used

**Comment by andrewvarga** [comment]
Sure, this is the error:
```
different objects that are equal by value. (more info at http://bit.ly/wdyr02)
whyDidYouRender.min.js?e4fb:8 
prev hsl: {a: 1, h: 0, l: 0.3333333333333333, s: 0.6823529411764706}
next hsl: {a: 1, h: 0, l: 0.3333333333333333, s: 0.6823529411764706}
```
so the objects are the same stringified but they are actually different by references.

The component looks like this:
```
const ColorPicker = memo(props => {
   ... component implementation
}, (prevProps, nextProps) => {
// deep check
})
export default CustomPicker(ColorPicker)
```
CustomPicker is a wrapper from this library, which injects these computed props like "hsl":
https://github.com/casesandberg/react-color

So basically I have no control over that part at the moment. I'm guessing in their implementation they update my ColorPicker component with different props instances even if the value hasn't changed, that's why I resorted to using "propsAreEqual".

**Comment by vzaidman** [comment]
what about making CustomPicker(ColorPicker) pure instead of the inner one?

**Comment by andrewvarga** [comment]
> what about making CustomPicker(ColorPicker) pure instead of ColorPicker?

How would I do that?

**Comment by vzaidman** [comment]
```
const ColorPicker = CustomPicker(props => {
   ... component implementation
})
export default memo(ColorPicker)
```

**Comment by andrewvarga** [comment]
Ah.
So what I did previously was this:
```
CustomPicker(memo(props => {
   ... impl
}))
```

your suggestion would be:
```
memo(CustomPicker(props => {
   ... impl
}))
```

meaning if the props don't change CustomPicker will not even get a chance to inject its own calculated props..sounds reasonable! I give it a quick test, the component doesn't update for some reason in certain cases, but might be a bug I haven't found yet.
 Thanks!

**Comment by vzaidman** [comment]
@andrewvarga does it works for you?

**Comment by andrewvarga** [comment]
> @andrewvarga does it works for you?

it seems to be yes. There is one warning still, but instead of props it comes from the "state" of the CustomPicker library...something I cannot really fix. But already the perf. improvements are very visible!

**Comment by vzaidman** [comment]
great!
you can also try using CustomPicker.whyDidYouRender = false

**Comment by vzaidman** [comment]
i mean
```js
const ColorPicker = memo(CustomPicker(props => {
   ... component implementation
}))
ColorPicker .whyDidYouRender = false
export default ColorPicker 
```
