### ISSUE TITLE
Possible bug when using multiple WDYR instances 

### ISSUE THREAD

**Issue by OnkelTem** [welldone-software/why-did-you-render#111]
So I continue my experiments with React render "mysteries" using WDYR and just come across a little strange behaviour when using multiple instances of WDYR with class-components.

Here is a sandbox: https://codesandbox.io/s/react-render-research-multiwdyr-eturn?file=/src/App.js

WDYR initialization is performed in the [wdyr.js](https://codesandbox.io/s/react-render-research-multiwdyr-eturn?file=/src/wdyr.js) and creates 3 instances. They're marked with numbers - 1, 2 and 3 and colors - red, green and orange:

```js
if (process.env.NODE_ENV === "development") {
  const options = (id, color) => ({
    include: [/.*/],
    notifier: ({displayName}) => {
      console.log(`%cWDYR(${id}): ${displayName}`, `color: ${color}`);
    }
  })
  const whyDiDYouRender1 = require("@welldone-software/why-did-you-render");
  whyDiDYouRender1(React, options(1, 'red'));
  const whyDiDYouRender2 = require("@welldone-software/why-did-you-render");
  whyDiDYouRender2(React, options(2, 'green'));
  const whyDiDYouRender3 = require("@welldone-software/why-did-you-render");
  whyDiDYouRender3(React, options(3, 'orange'));
}
```
The component of our interest is a class one - `A` declared in the [App.js](https://codesandbox.io/s/react-render-research-multiwdyr-eturn?file=/src/App.js): 
```js
class A extends React.Component {
  constructor(props) {
    super(props);
    console.log('A create', props);
  }
  render() {
    console.log('A render', this.props);
    return (
      <div>A {this.props.v}</div>
    );
  }
}
```

Now take a closer look at the console. We see there:
```
App render 
A create 
WDYR(2): A
WDYR(3): A
A render 
```
There are two oddities:

1. WDYR messages come _before_ rendering A. This is strange because from my experience WDYR shound't react on the first renders, only on the subsequent ones - i.e. _re-renders_. 

2. There are only two such messages - from the **2nd** and **3rd** instances, but the first one's is missed. 

Ideas?

**Comment by vzaidman** [comment]
two instances are not supported

**Comment by OnkelTem** [comment]
Sorry, what?

Yesterday we were discussing exactly **this case**:

https://github.com/welldone-software/why-did-you-render/issues/108

And you were actively participating, suggesting solutions using exactly **two** instances. As a matter of fact, w/o **two** instances the whole idea of using WDYR for logging _as a replacement of its normal application_ doesn't worth a penny. Huh..

Specifically here I came with exactly two instances solution:
https://github.com/welldone-software/why-did-you-render/issues/108#issuecomment-619364943

How comes it's not supproted since today?

**Comment by vzaidman** [comment]
i won't be surprised if two instances might work but i'm not actively supporting it
