### ISSUE TITLE
error: TypeError: Super expression must either be null or a function

### ISSUE THREAD

**Issue by wizevlad** [welldone-software/why-did-you-render#118]
#92

**Comment by vzaidman** [comment]
Copied from #92 since this is another error:

> I have `react-redux` v7.2.0. and `why-did-you-render` v4.2.0. Got this error:
> 
> Screen Shot 2020-05-11 at 12 48 55 PM
> ![image](https://user-images.githubusercontent.com/5188459/81647497-c35c3900-9435-11ea-81c5-24ff412c4e46.png)
> 
> Readable:
> ```
> error: TypeError: Super expression must either be null or a function
> ````

**Comment by vzaidman** [comment]
can you please specify in what scenario it happens?

i use react redux 7.2, and the library is tested with it so it has to be something more specific.

you can use the unminimized version of the library to debug it:
```
  let whyDidYouRender = require('@welldone-software/why-did-you-render/dist/cjs/whyDidYouRender.js')
  let ReactRedux = require('react-redux')
  whyDidYouRender(React, {
    trackAllPureComponents: true,
  })
```

also, make sure your "why did you render" is up to date

**Comment by vzaidman** [comment]
@wizevlad re-open when when you have more info.
