### ISSUE TITLE
different functions with the same name

### ISSUE THREAD

**Issue by DavidLozzi** [welldone-software/why-did-you-render#119]
I saw the other posts about this, I think I get the "why" behind it but not really tracking the "why" since I don't really know what the solution is here. 

Here's my code, all in one file:

```
export const Layout = (props) => {
...
  const goHome = () => {
    history.push(CONFIG.UI_URL.HOME);
  };

  return (
    <>
      <div className={`layout ${brand.CSS}`} id={id}>
        <header>
          <Grid>
            <Nav
              homeClickHandler={goHome}
            />
          </Grid>
        </header>
...
export default withRouter(connect(mapStateToProps, mapDispatchToProps)(memo(Layout)));
```

And I'm getting 
![image](https://user-images.githubusercontent.com/3543383/81696640-306dcf80-9432-11ea-902d-a991d7a6b1f3.png)

**Comment by vzaidman** [comment]
Currently, you have `goHome` invalidating `Nav` on every render of `Layout`.

What you need to do is to wrap `goHome` with `useCallback`.

It would memoize `goHome` and ensure `goHome` is **always the first `goHome` generated** so `Nav` would always receive the same `goHome`.

```
const goHome = React.useCallback(() => {
  history.push(CONFIG.UI_URL.HOME);
}, [history])
```

**Comment by vzaidman** [comment]
by the way, `connect` is wrapped with `memo` inside it by default, (you can dig into how to prevent it) and compares it's resulting props with shallow equality, so wrapping it again with memo is probably redundant.
```
withRouter(connect(mapStateToProps, mapDispatchToProps)(memo(Layout)));
```

**Comment by DavidLozzi** [comment]
THANK YOU!
