### ISSUE TITLE
Hooks are not supported

### ISSUE THREAD

**Issue by vzaidman** [welldone-software/why-did-you-render#12]
**functional components with hooks work as expected regarding their props.**

but we dont have a way right now to track state changes that are caused by the "useState" hook for example even if they trigger a render with similar state.

**Comment by joelstransky** [comment]
I assume you mean "useState" instead of "setState"
I can confirm that it complains about function components state even if I don't use useState. I would prefer to suppress the warning if possible until it can be accurate.

**Comment by panczarny** [comment]
I created a hook that checks render reason - https://gist.github.com/panczarny/0a392ad3f173d2b413f6c6240a770226

You just pass `props` and all the `state` variables.

*Important*
It doesn't cover case, when you are using custom hooks, and those hooks use their `useState`. There is no possibility to check this, unless you dive into React package. I didn't have enough time to check it, though I didn't do it yet - but it's ongoing 😸

**Comment by vzaidman** [comment]
it's nice but in version 3 im gonna add an actual support to hooks. its already in the beta version!

**Comment by vzaidman** [comment]
Hooks are supported in version 3:
https://github.com/welldone-software/why-did-you-render/releases/tag/v3.0.0

you can read about it [>> HERE <<](http://bit.ly/wdyr3)
