### ISSUE TITLE
Is react dev tool doing the same with their 'Profiler'?

### ISSUE THREAD

**Issue by 41y08h** [welldone-software/why-did-you-render#122]
I'm just new to this, but sorry if it's a vague question and if I wasted your time! :)

**Comment by vzaidman** [comment]
No.

react dev tools gives you the option to see why a component was rendered (prop change? hook change?) after the fact, if you go to react dev tool and explicitly look for it.

in WDYR, you mark which components the library tracks, and it tells you which renders on them could probably be prevented.
