### ISSUE TITLE
How to get it to work with CRA created app?

### ISSUE THREAD

**Issue by JohannesKlauss** [welldone-software/why-did-you-render#123]
How can I activate this package when using create-react-app?

In my index.ts I import the `wdyr.ts` in the first line:

`import './wdyr';`

And the wdyr.ts looks like this:

```ts
import React from 'react';
import whyDidYouRender from "@welldone-software/why-did-you-render";

(function wdyrPatch () {
  if (process.env.NODE_ENV === 'development') {
    console.log('Patch React with wdyr');

    whyDidYouRender(React, {
      titleColor: "green",
      diffNameColor: "aqua",
      trackAllPureComponents: true,
    });
  }
})();
```

But it still doesn't track any re-renders.

The HMR loads before React gets patched, I don't know it this is an issue. Is there a way to use this package with CRA?
<img width="507" alt="Bildschirmfoto 2020-07-05 um 17 09 37" src="https://user-images.githubusercontent.com/6214415/86535681-54093f80-bee2-11ea-974d-6d42af8c23a8.png">

**Comment by JohannesKlauss** [comment]
Sorry, my example was wrong. Everything works as expected.

**Comment by endquote** [comment]
I came here trying to do the same thing, but the above example doesn't seem to work for me. Should I be seeing something in the console for a normal update of a component when a prop changes?

wdyr.ts
```ts
import React from "react";
import whyDidYouRender from "@welldone-software/why-did-you-render";

(function wdyrPatch() {
  if (process.env.NODE_ENV === "development") {
    whyDidYouRender(React, {
      titleColor: "green",
      diffNameColor: "aqua",
      trackAllPureComponents: true,
    });
  }
})();
```

index.tsx
```ts
import "./wdyr";
import React from "react";
import ReactDOM from "react-dom";
import App from "./App";

ReactDOM.render(
  <React.StrictMode>
    <App />
  </React.StrictMode>,
  document.getElementById("root")
);
```

**Comment by endquote** [comment]
Nevermind, I got it working too.

I think the problem is that it doesn't fire if the property change is in the highest-level App component.

**Comment by vzaidman** [comment]
import whyDidYouRender from "@welldone-software/why-did-you-render";
means you will have it in bundled production @endquote

**Comment by endquote** [comment]
@vzaidman Alright, so then what is the recommended way to include it in a `create-react-app` template?

**Comment by vzaidman** [comment]
like in the readme:
```js
import React from 'react';

if (process.env.NODE_ENV === 'development') {
  const whyDidYouRender = require('@welldone-software/why-did-you-render');
  const ReactRedux = require('react-redux');
  whyDidYouRender(React, {
    trackAllPureComponents: true,
    trackExtraHooks: [
      [ReactRedux, 'useSelector']
    ]
  });
}
```
