### ISSUE TITLE
No logs

### ISSUE THREAD

**Issue by EstebanBP** [welldone-software/why-did-you-render#14]
I've installed this package and I'm using it on my react native project like this:
```
if (process.env.NODE_ENV !== 'production') {
  const whyDidYouRender = require('@welldone-software/why-did-you-render');
  whyDidYouRender(React);
}
```

But I get no log/error at all.

Do I need to do anything after install package?

```
"@welldone-software/why-did-you-render": "^3.0.0-beta.5",
"react": "16.8.3"
"react-native": "0.59.2"
```

**Comment by vzaidman** [comment]
copied from the readme:

two options:

1. mark all the components you want to be notified about their re-renders with `whyDidYouRender` like so:

```js
class BigListPureComponent extends React.PureComponent {
  static whyDidYouRender = true
  render(){
    return (
      //some heavy render you want to ensure doesn't happen if its not neceserry
    )
  }
}
```
Or like this:
```js
const BigListPureComponent = props => (
  <div>
    //some heavy component you want to ensure doesn't happen if its not neceserry
  </div>
)
BigListPureComponent.whyDidYouRender = true
```
Or track all the components that are matched by their name in the include array like this:
```
whyDidYouRender(React, { include: [/^pure/], exclude: [/^Connect/] });
```

**Comment by EstebanBP** [comment]
My bad, I should have read better.
Thanks!

**Comment by piotrkochan** [comment]
I've added some `myComp.whyDidYouRender = true` but still there is no logs

**Comment by vzaidman** [comment]
how do you use "myComp"? (by the way it sohuld probably be capital letter: "MyComp"

**Comment by rbrewington** [comment]
I also can't seem to see any logs. Is this some issue with functional components?

**Comment by vzaidman** [comment]
try the example here:
https://github.com/welldone-software/why-did-you-render/issues/14#issuecomment-479457077

there are only logs if renders can be prevented.

**Comment by vzaidman** [comment]
```
  whyDidYouRender(React, {
    trackAllPureComponents: true,
  });
```
would track all pure components. does it answer your question?
what do you mean by "conditionally rendered"?

**Comment by rbrewington** [comment]
I made an issue specific to my use case: https://github.com/welldone-software/why-did-you-render/issues/94

By conditionally rendered, I mean it's only rendered under certain conditions.

**Comment by StuartFlutter** [comment]
I just tried to use whyDidYouRender, have installed it correctly and followed instructions exactly, and still see no logged output of any kind

**Comment by dimashpt** [comment]
React native has different development flag than react for web
Just change your condition from
`if(process.env.NODE_ENV !== 'production')`
to:
`if (__DEV__)`

And viola
