### ISSUE TITLE
when are prevProps and nextProps passed in to the notifier function?

### ISSUE THREAD

**Issue by chadi-kazan** [welldone-software/why-did-you-render#148]
`notifier: ({Component, displayName, prevProps, prevState, nextProps, nextState, reason, options}) => void`
they are always undefined for hooks. it would help to have them so we can have finer grained control over the notifications.

**Comment by vzaidman** [comment]
hey!
i updated the readme to reflect that the real obj keys are:
```
- `notifier: ({Component, displayName, hookName, prevProps, prevState, prevHook, nextProps, nextState, nextHook, reason, options, ownerDataMap}) => void`
```
