### ISSUE TITLE
`trackAllPureComponents` is not working

### ISSUE THREAD

**Issue by thanhtoan1196** [welldone-software/why-did-you-render#151]
I am using Next.js and install as follows

_app.tsx
```
if (typeof window !== 'undefined' && process.env.NODE_ENV === 'development') {
    const whyDidYouRender = require('@welldone-software/why-did-you-render');
    whyDidYouRender(React, {
        trackAllPureComponents: true,
    });
}
```

But it doesn't work without using `whyDidYouRender = true`, for example
```
Search.whyDidYouRender = true
export default Search
```

**Comment by vzaidman** [comment]
can you try adding the code in a separate file like described in the readme please?
https://github.com/welldone-software/why-did-you-render#installation

**Comment by thanhtoan1196** [comment]
hi @vzaidman, I tried adding the code in a separate file, but it is not working
https://gitlab.com/thanhtoan1196/next-test

I test component `Search`

**Comment by vzaidman** [comment]
it's just that in your application no redundant renders are happening. Try this:
```
import React, { useState } from 'react';

function Search() {
  const [query, setQuery] = useState({str: 'aa'});
  return (
      <div>
        <input type="text" value={query.str} onChange={(e) => setQuery({str: 'aa'})}/>
        <div>value: {query.str}</div>
      </div>
  )
}

Search.whyDidYouRender = true
export default Search
```

**Comment by thanhtoan1196** [comment]
@vzaidman I want to use `trackAllPureComponents: true` instead of `whyDidYouRender = true` for each component
Your example doesn't work without `Search.whyDidYouRender = true`

**Comment by vzaidman** [comment]
then make it pure:
```
import React, { useState, memo } from 'react';

const Search = memo(() => {
  const [query, setQuery] = useState({str: 'aa'});
  return (
      <div>
        <input type="text" value={query.str} onChange={(e) => setQuery({str: 'aa'})}/>
        <div>value: {query.str}</div>
      </div>
  )
})

export default Search
```

**Comment by thanhtoan1196** [comment]
ok I got it, thanks
