### ISSUE TITLE
This package should be a dev dependency?

### ISSUE THREAD

**Issue by sanehab** [welldone-software/why-did-you-render#152]
This package should be a dev dependency, however in the readme, the instruction to install it is:
```
npm install @welldone-software/why-did-you-render --save
```

This might cause some production bundles to get unnecessarily bigger.

Thanks

**Comment by vzaidman** [comment]
bundles depend on what you import and not what you add to `package.json`.
as lonmg as you add it like this:
```
if (process.env.NODE_ENV === 'development') {
  const whyDidYouRender = require('@welldone-software/why-did-you-render');
  whyDidYouRender(React, {
    trackAllPureComponents: true,
  });
}
```
your buncle should not change

**Comment by sanehab** [comment]
Thanks for answering me, i was thinking about the case when the require statement will be replaced with an es6 import statement, and i thought that due to the fact that import statements are hoisted this will cause the module to be required even in production build. But apparently - which is something that i did not know - the es6 spec does not allow an import statement to be inside an if statement or any other block statement.

However i still believe that it is better to have the intention clear that this is a dev dependency, this creates a standardized structure that makes it easier to build upon, for example: this enables smart bundlers to give warnings when a dev dependency is being included in prod bundle, this also gives security tools better visibility into what should be audited more carefully, a dev dependency might require more loose checks that a production dependency.

Thanks
