### ISSUE TITLE
Cannot create property 'current' on number '2'

### ISSUE THREAD

**Issue by DalderupMaurice** [welldone-software/why-did-you-render#156]
During development, I've encountered the following issue: `Cannot create property 'current' on number '2'`

I actually have no idea how it gets triggered, but it seems to happen when CRA is recompiling/updating after code changes. 
I've updated CRA to 4.0, which uses Fast Refresh instead of React Hot Reloader, which might be a lead to the issue as it happens when it is refreshing after a code change and the problem started after upgrading the stack.

Another important detail is if we look at the last error log down below...

The line ` const theme = useSelector((state) => state.x.theme);` is data retrieved from react context (which is retrieved from a provider supplied by `styled-components` and changes are propagated through redux), so it might also have to do something with the `useContext` (which the stack trace mentions in the 2nd and 3rd error log as a title) 

Detail of the error logs: 
```javascript
te...path/whyDidYouRender.js:23
  20 | if(hooksRef.current[0] && renderNumber.current !== hooksRef.current[0].renderNumber){
  21 |   hooksRef.current = []
  22 | }
> 23 | hooksRef.current.push({hookName, result: nextHook, renderNumber: renderNumber.current})
     | ^  24 | renderNumber.current++
  25 | const ComponentHookDispatchedFromInstance = (
  26 |   React.__SECRET_INTERNALS_DO_NOT_USE_OR_YOU_WILL_BE_FIRED &&
```

```javascript
UseContext ...path/whyDidYouRender.js:245
  242 | const hookResult = originalHook.call(this, ...args)
  243 | const {dependenciesPath, dontReport} = hookTrackingConfig
  244 | if(dependenciesPath && isFunction(hookResult)){
> 245 |   dependenciesMap.set(hookResult, {hookName, deps: get(args, dependenciesPath)})
      | ^  246 | }
  247 | if(!dontReport){
  248 |   trackHookChanges(hookName, hookTrackingConfig, hookResult, React, options, ownerDataMap, hooksRef)
```

```javascript
UseContext ...path/whyDidYouRender.js:241
  238 |      const originalHook = hookParent[hookName]
  239 |      const newHookName = hookName[0].toUpperCase() + hookName.slice(1)
  240 | 
> 241 |      const newHook = function(...args){
      | ^  242 |        const hookResult = originalHook.call(this, ...args)
  243 |        const {dependenciesPath, dontReport} = hookTrackingConfig
  244 |        if(dependenciesPath && isFunction(hookResult)){
```

```javascript
App/App.tsx:34
  31 | };
  32 | 
  33 | const App = React.memo(() => {
> 34 |   const theme = useSelector((state) => state.x.theme);
....
```

**Comment by vzaidman** [comment]
I'll look at it. thanks

**Comment by vzaidman** [comment]
It has to do with how useSelector.
did you add it to WDYR as a custom hook?

**Comment by DalderupMaurice** [comment]
> It has to do with how useSelector.
> did you add it to WDYR as a custom hook?

This is how my import looks like, I'm not sure why I disabled trackAllPureComponents a while back
```
  const whyDidYouRender = require("@welldone-software/why-did-you-render");
  whyDidYouRender(React, {
    trackAllPureComponents: false // TODO enable this
  });
```

& useSelector is a re-exported typed version:
```
import {
  useSelector as useReduxSelector,
  TypedUseSelectorHook
} from "react-redux";
import { RootState } from "../redux/config/combinedReducers";

const useSelector: TypedUseSelectorHook<RootState> = useReduxSelector;

export default useSelector;

```

Although I just noticed that `TypedUseSelectorHook` seems to be deprecated.

**Comment by vzaidman** [comment]
are you sure the problem is related to the library? did you try disabling it?

**Comment by DalderupMaurice** [comment]
> are you sure the problem is related to the library? did you try disabling it?

I haven't had the time to extensively try it out, but disabling it did not trigger it for the short time I worked on it. 
Will revisit it soon to confirm
