### ISSUE TITLE
static whyDidYouRender = true doesn't have any effect in 5.0.0 

### ISSUE THREAD

**Issue by Slapbox** [welldone-software/why-did-you-render#158]
Using `trackAllPureComponents: true` works fine, but using the static method doesn't do anything after upgrading.

**Comment by vzaidman** [comment]
it has. please check:
https://codesandbox.io/s/84xv0nk310.
you are free to reopen the issue if I've missed anything

**Comment by Slapbox** [comment]
Thanks for your reply @vzaidman! Looks good! It hadn't been working for us locally but that too has mysteriously resolved ¯\\\_(ツ)\_/¯

**Comment by Slapbox** [comment]
Thanks for your reply @vzaidman! Looks good! It hadn't been working for us but that seems to have mysteriously resolved ¯\\\_(ツ)\_/¯

**Comment by vzaidman** [comment]
can you please try version `6.0.0-rc.1` ? :)
