### ISSUE TITLE
Not working with forwardRef

### ISSUE THREAD

**Issue by mrondra** [welldone-software/why-did-you-render#161]
Hi,

I have a problem with forwardRef and Typescript. Example below:

```
const Heading = forwardRef<HTMLHeadingElement, HeadingProps>(function headingFunction(
    props: HeadingProps,
    ref,
): ReactElement<HeadingProps, HeadingProps['tag']> | null {
    ...
});

Heading.whyDidYouRender = true;     
```

And I get this error:
```
TS2339: Property 'whyDidYouRender' does not exist on type 'ForwardRefExoticComponent  >'
```

Do you have any idea what to do with it?

Thank you

**Comment by vzaidman** [comment]
interesting. it seems to work for me:
![image](https://user-images.githubusercontent.com/5188459/100432258-00baa800-30a2-11eb-8f3a-0294efc743d3.png)

try reinstalling the app:
```
yarn add @welldone-software/why-did-you-render --force
```

**Comment by mrondra** [comment]
Great, it works, thank you very much.

**Comment by vzaidman** [comment]
somehow, it was adding the types automatically up until now.

however, it seems like we need to add it manually in the latest typescript versions.

I'm adding a section about it in the readme.

thanks for noticing and reporting the problem!
