### ISSUE TITLE
Mobx Support

### ISSUE THREAD

**Issue by thunderkid** [welldone-software/why-did-you-render#162]
Is this library compatible with Mobx?

I'm trying to adapt the [why-did-you-render official example ](https://codesandbox.io/s/6vowz0w2wz?expanddevtools=1&file=/src/index.js) to run with Mobx 5.
As soon as I put a `@observer` decorator above `BigListPureComponent`, I stop getting any `why-did-you-render` console notifications. 
```
@observer
class BigListPureComponent extends React.PureComponent {
  static whyDidYouRender = true;
  render() {
    console.log(
      "BigListPureComponent Re-Render! - We don't want to get here too often."
    );
    return (
      <div style={this.props.style}>
        <h2>BigListPureComponent</h2>
        <div>
          {times(3000).map(n => (
            <div key={n}>Element #{n}</div>
          ))}
        </div>
      </div>
    );
  }
}
```
However, I still get the regular `console.log` notification, so it's clearly still being rendered unnecessarily. I've tried multiple permutations such as extending from `React.Component`, but as soon as I add in `@observer` it stops working.

Is there an example of this library working with `Mobx` or are they incompatible? I don't see any mention in the docs one way or the other. Thanks.

**Comment by vzaidman** [comment]
Can you add a link to a sandbox of this sort please?

**Comment by vzaidman** [comment]
How do you see mobx support?

For now, we don't support it because of the amount of magic it uses.

I added initial `tests` and `start` sandbox here for those who want to play with it:
https://github.com/welldone-software/why-did-you-render/pull/169

**Comment by vzaidman** [comment]
I looked at mobx again - I don't believe the library will support it because of how mobx causes re-renders.
We can't really know `why-did-you-render` if you swallow the logic and cause a re-render on your own terms.
I mean, it's not a criticism, mobx is an amazing library. It's just not compatible with `WDYR`
