### ISSUE TITLE
component show as unknown

### ISSUE THREAD

**Issue by eliyahu-dayan-1** [welldone-software/why-did-you-render#163]
I have unknown component while component has a name. 
Why it is?

![image](https://user-images.githubusercontent.com/62394293/101362449-c8d51100-38a8-11eb-8aae-36827461bea1.png)

**Comment by eliyahu-dayan-1** [comment]
I answer to myself that because the const who export was wrapping with React.memo()

such as

`
const MenuGridItems = React.memo(() => {
   return <div>somthing</div>
})

return MenuGridItems
`

after I fixed

const MenuGridItems = () => {
   return <div>somthing</div>
}

return React.memo(MenuGridItems)
`

**Comment by vzaidman** [comment]
what about
```jsx
return React.memo(function MenuGridItems() {
   return div somthing div
})
```
?

**Comment by eliyahu-dayan-1** [comment]
@vzaidman 
it's good also, 
but in my company this is the syntax.

by the way do you think my syntax has a probllem?

**Comment by vzaidman** [comment]
It's ok!
