### ISSUE TITLE
Reporting that component re-renders due to forceUpdate when in reality it's re-renders because of the father component

### ISSUE THREAD

**Issue by brenoo2018** [welldone-software/why-did-you-render#166]
On the console of my browser it shows the following message, however I am not using this.forceUpdate () function.
"Re-rendered although props and state objects are the same." "This usually means there was a call to this.forceUpdate() inside the component."
See the print below :

![Screenshot_20201215_100920](https://user-images.githubusercontent.com/37019853/102219618-799d6a80-3ebe-11eb-953e-55babc080ad2.png)

**Comment by vzaidman** [comment]
it's very rare that a component re-renders by itself without any changes to state or props. do you know what changes indeed?

**Comment by brenoo2018** [comment]
Yes @vzaidman , I am using the library to identify which props, states and functions are unnecessarily re-rendering and according to the logs, I will be doing the checks in shouldComponentUpdate to control such renderings. However it is showing this print message about the this.forceUpdate () function that is causing such re-renderings but I am not using it, I saw that there is a closed issue on this same subject here that some user reported to be about StrictMode but not I'm using it, so I opened this other issue.

**Comment by vzaidman** [comment]
can you try to wrap the component with "React.memo"?

**Comment by vzaidman** [comment]
ok i checked it.

seems like your error is probably really:
```
"Re-rendered because the props object itself changed but its values are all equal." "This could have been avoided by making the component pure, or by preventing its father from re-rendering." "More info at http://bit.ly/wdyr02" 
```

**Comment by vzaidman** [comment]
there's a bug in the library with the latest version of React that it also reports this specific error. i need to check it.

i think your component re-renders because it's rendering component re-renders.

**Comment by vzaidman** [comment]
you can see it here:
https://codesandbox.io/s/why-did-you-render-sandbox-forked-dsdy8
if you update react to latest version on the left, you will see both messages instead of the correct one.

**Comment by brenoo2018** [comment]
I am using version v5.0, I had put the most recent but it caused me an error of Uncaught RangeError: Maximum call stack size exceeded, then I changed to a previous version.
My component is classy, I was using React.PureComponent but as I am using the shouldComponentUpdate () function to control the renderings I switched to the Component, but my component keeps re-rendering due to this message that the forceUpdate function is being call.

**Comment by brenoo2018** [comment]
How can I solve? I can't identify the reason for the re-rendering so I can prevent it.

**Comment by vzaidman** [comment]
oh i see.
it's probably because your `shouldComponentUpdate` doesn't return `false` when the components are equal.
`prevProps === nextProps`
why do you need `shouldComponentUpdate`? can't use make it pure and that's it?

also, I suggest updating all packages to latest versions

**Comment by brenoo2018** [comment]
@vzaidman I decided to use an earlier version of this library because as I reported it showed me an error and the page broke, or when it didn't, it didn't show me the logs.
About PureComponent it was not preventing the screen from re-rendering, so I decided to manually control it with shouldComponentUpdate (), and the renderings decreased because I'm doing the necessary comparisons, however this implicit this.forceUpdate function is causing other unnecessary re-renderings as shown in the print logs of this issue, but this function does not exist in my component so I am unsolved.

**Comment by vzaidman** [comment]
React 16.6 is very old. better update it. I'm not sure how the library works with it.

**Comment by brenoo2018** [comment]
@vzaidman I work at a company that is using react in this version, the software is 3 years old, to update the version I would have to talk to the team.

**Comment by vzaidman** [comment]
ok. i suggest to not use WDYR with this old version.

**Comment by vzaidman** [comment]
hey @brenoo2018 !
do you add WDYR in a separate file like here:
https://github.com/welldone-software/why-did-you-render#setup
and like in this sandbox:
https://codesandbox.io/s/why-did-you-render-sandbox-forked-dsdy8?file=/src/index.js
?

**Comment by brenoo2018** [comment]
Hi @vzaidman !! 
I'm using lib WDYR in a separate file, I installed version 5.0
