### ISSUE TITLE
[NEXT.JS] TypeError: Object.defineProperty called on non-object

### ISSUE THREAD

**Issue by abnersajr** [welldone-software/why-did-you-render#17]
I'm facing issues using NextJs. I'd tried different ways to do it but always the same results.
Even in build mode and dev mode, the issue is the same just change the file names because of the hashes.

I import React globally, so I don't have to put: `class NameClass extends React.Component`/

I also tried to import in different scenarios mentioned in the doc and also using require and import, but didn't work.

I don't have any modifications in babel plugins and etc, but NextJS have their own.
This is preset:
https://github.com/zeit/next.js/blob/canary/packages/next/build/babel/preset.ts

I think that looking into this you can assume if any plugin is causing this issue.

In this screenshot is the issue when I start a server with builded version:
<img width="1184" alt="Screen Shot 2019-04-10 at 10 10 41" src="https://user-images.githubusercontent.com/1998649/55881689-814d2d80-5b79-11e9-96e2-f43bda885469.png">

**Comment by abnersajr** [comment]
Here is a screenshot when I'm running `yarn dev`, the built-in version:

<img width="1147" alt="Screen Shot 2019-04-10 at 10 35 41" src="https://user-images.githubusercontent.com/1998649/55883415-ad1de280-5b7c-11e9-9f7c-e787777b67e7.png">

**Comment by vzaidman** [comment]
Hey!
First of all, I work with the library with next.js as well so the preset is not the problem.

**Comment by vzaidman** [comment]
Can you try the `trackHooks: false` option when initializing the library?

**Comment by abnersajr** [comment]
I don't use hooks, but yes I can try. I use the version `16.6.1`

**Comment by vzaidman** [comment]
can you update to latest react and try again?

**Comment by abnersajr** [comment]
Where exactly do you import the `WhyDidYouRender`?

**Comment by vzaidman** [comment]
in _app

**Comment by abnersajr** [comment]
👌 Ita working. I will make a PR with some sdditions in the docs about it.
Thanks for your effort.

**Comment by vzaidman** [comment]
instead of PR to docs, make a PR that doesn't runs hooks if the hooks object is not on React so we will support older versions.

**Comment by vzaidman** [comment]
updated the requirement for the library to version ***>=16.8***

**Comment by crapthings** [comment]
this still exist

**Comment by vzaidman** [comment]
exists on latest react?

**Comment by crapthings** [comment]
![image](https://user-images.githubusercontent.com/1147704/64520838-816c7780-d329-11e9-9380-6443a3be20c8.png)

**Comment by vzaidman** [comment]
What polyfill do you use?

**Comment by crapthings** [comment]
default meteor 1.8.1 sets ?

https://github.com/meteor/babel/blob/master/package.json

**Comment by vzaidman** [comment]
please use the non-minified version of whyDidYouRender

**Comment by vzaidman** [comment]
can be reopened when more information is provided.
