### ISSUE TITLE
Snowpack example

### ISSUE THREAD

**Issue by techieshark** [welldone-software/why-did-you-render#170]
I'm testing out Snowpack which wants to use import rather than `require()`, so I've changed my index file to that shown below. 

I was surprised to find no other issues related to Snowpack, so perhaps others were able to get things working without this. In any case, I thought I'd add it here in case others find it useful.

Implementation notes:

1. It uses the dynamic import (`import()`) to import only in development.
2. In Snowpack, `import.meta.env.MODE` is the equivalent to Create React App's `process.env.NODE_ENV`
3. This uses why-did-you-render's `include` option to only show re-renders for components matching the regex `/App/`. Users should change this as needed.

```
// index.tsx
import React from 'react';
import ReactDOM from 'react-dom';

import App from './App';
import * as serviceWorker from './serviceWorker';

function renderPage() {
  const rootElement = document.getElementById('root');
  ReactDOM.render(<App />, rootElement);
}

async function catchRerendersInDev() {
  // "monkey patches React to notify you [in console] about avoidable re-renders."
  if (import.meta.env.MODE !== 'production') {
    const whyDidYouRender = await import('@welldone-software/why-did-you-render');
    whyDidYouRender.default(React, { include: [/App/] });
  }
}

catchRerendersInDev().then(renderPage);

// If you want your app to work offline and load faster, you can change
// unregister() to register() below. Note this comes with some pitfalls.
// Learn more about service workers: http://bit.ly/CRA-PWA
serviceWorker.unregister();
```

**Comment by vzaidman** [comment]
Thank you for the effort!

Also, it's nice it works for you, but the async import is **dangerous** and might cause bugs in other cases.

f.e if you have imports where react elements are created not as part of the man render:
```jsx
import React.js

const emptyDiv = <div></div>
```
are you sure there's no way to import it synchronously?

I also suggest moving the wdyr code to a separate file: `wdyr.js`
