### ISSUE TITLE
why-did-you-render causes hooks issue with Chakra Toast

### ISSUE THREAD

**Issue by mikecx** [welldone-software/why-did-you-render#171]
I've submitted a full bug report to [Chakra](https://github.com/chakra-ui/chakra-ui) here https://github.com/chakra-ui/chakra-ui/issues/2924 , but i'm unsure if the bug is in Chakra or why-did-you-render.

When using why-did-you-render with `trackHooks: true` (the default), the hooks for the [Chakra Toast](https://chakra-ui.com/docs/feedback/toast) become out of order, the code breaks, and an error is thrown in the console.

Replication is available here: https://codesandbox.io/s/nice-kirch-n6r6c .

Current workaround is to set `trackHooks: false`, however that means i'm not getting the most out of this library.

**Comment by vzaidman** [comment]
As far as I can see, installing the library correctly in a separate file- fixes the issue:
https://codesandbox.io/s/sad-jepsen-47fj5?file=/src/wdyr.js

see the installation guides in the readme:
https://github.com/welldone-software/why-did-you-render#setup
