### ISSUE TITLE
Problem with TS4.1 + WP5 "Cannot set property createElement of [object Module] which has only a getter"

### ISSUE THREAD

**Issue by mastrzyz** [welldone-software/why-did-you-render#173]
It looks like with the recent upgrade to TS4/ WP5 made a lot of the modules more strict in ES6 mode. 

Specifically it looks like the React module now only has getters for all of its methods : 

![image](https://user-images.githubusercontent.com/37447884/103852440-ba714500-5060-11eb-95ca-2bc197d7ae38.png)

```ts
  import * as React from "react";
  whyDidYouRender(React, { ...defaultOptions, ...options });
```

This leads to a runtime error : 
![image](https://user-images.githubusercontent.com/37447884/103852518-dbd23100-5060-11eb-857e-4e7896091c76.png)

Version :  "@welldone-software/why-did-you-render": "^4.1.2",

Has anyone had any problems like this before?

**Comment by vzaidman** [comment]
hey!
before i investigate this, try the latest version of the library please

**Comment by mastrzyz** [comment]
@vzaidman  nevermind, looks like this is a known issue -> https://github.com/welldone-software/why-did-you-render/issues/85
