### ISSUE TITLE
WDYR not working with webpack-dev-server 

### ISSUE THREAD

**Issue by expertup** [welldone-software/why-did-you-render#175]
I would like to add WDYR to my script, I'm using webpack-dev-server. However, I don't see any logs in the console, and state changes in sub-components are because I can see how slow the page is rendering.

What am I doing wrong? Do I need to add anything to the WDS? Or just place the WDYR script somewhere else?

Below is the structure of my index.js file where I add WDYR.

```
import React from 'react';

 if (process.env.NODE_ENV !== 'production') {
	const whyDidYouRender = require('@welldone-software/why-did-you-render');
	whyDidYouRender(React, {
	  trackAllPureComponents: true,
	  logOnDifferentValues: true
	});
}

import ReactDOM from 'react-dom';

import { BrowserRouter, Router, withRouter, Switch, Route, Link } from "react-router-dom";
import createBrowserHistory from 'history/createBrowserHistory'

const newHistory = createBrowserHistory();


import Base from './pages/base';
import Main from './pages/main';

import './style.css'

import { MuiThemeProvider, createMuiTheme } from "@material-ui/core/styles";

const iOS = /iPad|iPhone|iPod/.test(navigator.userAgent);

const theme = createMuiTheme({
  palette: {
    primary: { main: '#3c4043'},
    secondary: { main: '#bdc1c6' }
  }
});

class App extends React.Component {
  constructor(props) {
    super(props)
	this.state = {
		
	}
  }
  render() {
    return (
		<BrowserRouter>
		  <Route path="/" component={props => {
			const c = (window.location.hostname.match(/\./g)||[]).length;
			if (c === 3) return <Base {...props}/>;
			return <Main {...props}/>;
		  }}/>
		</BrowserRouter>
    )
  }
}
export default App;

const rootElement = document.getElementById("app");

if (module.hot) {
	ReactDOM.render(<App />, rootElement);
}else{
	if (rootElement.hasChildNodes()) {
		ReactDOM.hydrate(<App />, rootElement);
	} else {
		ReactDOM.render(<App />, rootElement);
	}
}
```

**Comment by vzaidman** [comment]
please look at the readme again. wdyr should be added in a separate file: `wdyr.js`

**Comment by expertup** [comment]
> please look at the readme again. wdyr should be added in a separate file: `wdyr.js`

My mistake have be with wrong component type. I had `React.Component` not` React.PureComponent` or `React.Memo`. After change React compnent type WDYR working. And I don't must move code to separate file `wdyr.js`. Added this code only to first line main file and WDYR is working.

`webpack-dev-server` has nothing to do with it. Maybe someone will have a similar problem, find this thread and find a solution.

Thanks for the tip.

**Comment by vzaidman** [comment]
Great

> And I don't must move code to separate file wdyr.js

sometimes it might work, but this might break with some libraries. I do suggest moving it to `wdyr.js` and import it as first import.
