### ISSUE TITLE
How to use with Electron with nodeIntegration: false?

### ISSUE THREAD

**Issue by Slapbox** [welldone-software/why-did-you-render#180]
Electron's [`nodeIntegration: false`](https://quasar.dev/quasar-cli/developing-electron-apps/node-integration#What-won%E2%80%99t-work-when-turning-it-off) results in `require` being a noop except in the preload script - but the preload script has nothing to do with React.

We've tried a number of things to get this working. We've tried:

- Importing `wdyr.js` at the top of our preload script
- Importing at the top of our renderer script (the place it would normally be imported without a preload script - but without `require` this can't work)
- Improrting whyDidYouRender into the preload script, assigning it to `window.api.whyDidyouRender` and then importing `wdyr.js` in our renderer script but with the following code:

```js
if (IS_DEV) {
  window.api.whyDidYouRender(React, {
      trackAllPureComponents: true,
    });
}
```

Unfortunately none of these have resulted in whyDidYouRender messages appearing.

Any ideas?

**Comment by vzaidman** [comment]
No idea. Do you have some sort of public repository that I can clone with an example environment?

**Comment by Slapbox** [comment]
Som I'm an idiot. `IS_DEV` should have been `IS_DEV_ENV`. Created a whole repro to realize that mistake...

So for anyone who ends up here, you just `import './wdyr'` like normal - not in your preload script, and it will work fine as long as you don't make the code unreachable. Agh...

Thank you very much though for your reply @vzaidman.

**Comment by vzaidman** [comment]
I'm glad it works for you!
