### ISSUE TITLE
Error: Should have a queue 

### ISSUE THREAD

**Issue by ncioj10** [welldone-software/why-did-you-render#181]
Hi,
I am trying to install why did you render in a umi/ant design pro based application.
As I don't have access to the root element I tried adding it on the most outer level I can reach (which would be enough for recording). Unfortunately I am getting the following error:

```
Error: Should have a queue. This is likely a bug in React. Please file an issue.
▼ 4 stack frames were expanded.
updateReducer
./node_modules/react-dom/cjs/react-dom.development.js:15043
updateState
./node_modules/react-dom/cjs/react-dom.development.js:15237
useState
./node_modules/react-dom/cjs/react-dom.development.js:15949
useState
./node_modules/react/cjs/react.development.js:1508
▲ 4 stack frames were expanded.
UseState [as useState]
./src/whyDidYouRender.js:183
  180 |      const newHookName = hookName[0].toUpperCase() + hookName.slice(1);
  181 | 
  182 |      const newHook = function(...args) {
> 183 |        const hookResult = originalHook.call(this, ...args);
      | ^  184 |        const { dependenciesPath, dontReport } = hookTrackingConfig;
  185 |        if (dependenciesPath && isFunction(hookResult)) {
  186 |          dependenciesMap.set(hookResult, { hookName, deps: get(args, dependenciesPath) });

```

![image](https://user-images.githubusercontent.com/10393747/109816131-b01e9200-7c30-11eb-9d57-a9ec1f2afdee.png)

My steps are creating the wdyr.js and importing it as the first import after React. I wasn't sure if there are any other changes to be made.

Thanks in advance
Nico

**Comment by vzaidman** [comment]
This indeed seems to be a problem with improving it too late, where some React elements were already created without the library. Later when they re-render with the library it brakes some hooks.

Try to find a way to run it before the creation of any React element.
