### ISSUE TITLE
[Feature Request] Track ALL Components (not just pure)

### ISSUE THREAD

**Issue by matthewkwong2** [welldone-software/why-did-you-render#182]
As the title suggests, add a global property `trackAllComponents`, which as the name suggests, tracks every component imported. 
This is equivalent to adding `whyDidYouRender = true` in every component.

```js
whyDidYouRender(React, {
  trackAllComponents: true
});
```

**Comment by vzaidman** [comment]
while you can do it with:
```
whyDidYouRender(React, {
  include: [/.*/],
});
```
I strongly suggest against it, because all the noise you will get this way.
It's better, in my opinion, to focus on components marked as "gatekeepers" of big render trees by being pure.
