### ISSUE TITLE
Get Error when start dev server

### ISSUE THREAD

**Issue by TomJerryTheHandsome** [welldone-software/why-did-you-render#183]
At first the log works perfectly, after a few seconds the page went blank and got following error:
![image](https://user-images.githubusercontent.com/45165071/110470843-562d3900-8116-11eb-85c4-7f6156f9e415.png)
![image](https://user-images.githubusercontent.com/45165071/110470974-7d840600-8116-11eb-902d-276decece2ed.png)

**Comment by TomJerryTheHandsome** [comment]
My configuration:

trackAllPureComponents: true,
  onlyLogs: true,
  logOnDifferentValues: true,

**Comment by vzaidman** [comment]
Hey!
Are you sure that:
1. you have created a wdyr.js file and imported it as the first import in your application.
2. does it works correctly without the library?
3. did you restart the hot reload server (re-run `yarn dev` or the equivalent command)

**Comment by vzaidman** [comment]
you are free to keep the discussion and I'll reopen the ticket if there's any problem

**Comment by TomJerryTheHandsome** [comment]
@vzaidman We're using ts-loader to build out project instead of babel. 
1, I did import wdyr.js file as the first import in the application as the demo shows
2, The application functioning well without wdyr.js

**Comment by TomJerryTheHandsome** [comment]
@vzaidman The error locates in a  Provider component. Here is the code:
![image](https://user-images.githubusercontent.com/45165071/112787514-45c00c80-908b-11eb-9e6a-dd0ef8a73191.png)
and the return statement:
![image](https://user-images.githubusercontent.com/45165071/112787528-4eb0de00-908b-11eb-9a26-feeb64ecdfcf.png)
