### ISSUE TITLE
6.1 broken with mobx-state-tree 

### ISSUE THREAD

**Issue by cherepanov** [welldone-software/why-did-you-render#184]
We have complex legacy app with both redux and mobx-state-tree. WDYR turned on for all components.
And it worked fine until 6.1 release. Now after model update array values transformed to undefined's.

```
whyDidYouRender(React, {
        trackExtraHooks: [[require('react-redux'), 'useSelector']],
        include: [/^ConnectFunction/],
        trackAllPureComponents: true,
        trackHooks: true,
        logOwnerReasons: true,
        collapseGroups: true,
        hotReloadBufferMs: 1500
    });
```

**Comment by vzaidman** [comment]
Hey!
can you give me an example of a component that breaks?

**Comment by cherepanov** [comment]
I'll try to provide isolated case, i need some time to to untangle all our stuff. Obviously breaking change done by latest feature with tracking non plain objects, probably proxies are handled in a wrong way. May this feature should be configurable?

**Comment by vzaidman** [comment]
Yes it looks related to proxies, but there are no setters, only getters in the app so I'm not sure what could have gone wrong there...

I will make it configurable in case I couldn't fix this problem, but I believe I will fix it as soon as you provide an example.
You can for the official sandbox to do it: http://bit.ly/wdyr-sb

**Comment by vzaidman** [comment]
fixed in https://github.com/welldone-software/why-did-you-render/releases/tag/v6.1.1

**Comment by cherepanov** [comment]
Yep, it is not mangling data now. But i see extreme slowdown. Tens times slower than with 6.0.5.

**Comment by vzaidman** [comment]
@cherepanov would you mind checking what slows your app the most using the performance monitor, please?
