### ISSUE TITLE
How to handle props from multiple hooks?

### ISSUE THREAD

**Issue by hengvenchang** [welldone-software/why-did-you-render#186]
I have a list component the render items, but since list component relies on multiple props from multiple hooks, i got an warning every time one of it got update, 

const {data} = useDat()
const {option} = useOption()

<list data={data} option={option}/>

Suppose data is fetch from server which takes 1 second, And when data is arrived, I set data to a new state, Now list got to update, but it got warning since option has the same value

**Comment by vzaidman** [comment]
is the problem is that the results from the server is the same?

**Comment by vzaidman** [comment]
Please re-open if it's still relevant
