### ISSUE TITLE
Different functions with the same name

### ISSUE THREAD

**Issue by zcmgyu** [welldone-software/why-did-you-render#187]
## Description:

I got rerendering issue while use const { t } = useTranslation() of react-i18next. 
In my research, the inside of useTranslation hook used useState to store a getT function. Wrapping getT function inside useCallback hook could not prevent getting this message from WDYR

> different functions with the same name

```javascript
function getT() {
    return i18n.getFixedT(null, i18nOptions.nsMode === 'fallback' ? namespaces : namespaces[0]);
}
```
https://github.com/i18next/react-i18next/blob/master/src/useTranslation.js#L42-L45

```javascript
setT(getT);
```
https://github.com/i18next/react-i18next/blob/master/src/useTranslation.js#L82

Could you please confirm that issue comes from react-i18next? Thanks 🙇🏻 

## Reproduction:

Repo: https://github.com/zcmgyu/react-i18next-rerender-issue

<img width="662" alt="Screen Shot 2021-04-06 at 12 33 17" src="https://user-images.githubusercontent.com/13638569/113655197-55b39e00-96d4-11eb-8e47-dc6426635691.png">

<img width="896" alt="Screen Shot 2021-04-06 at 12 33 33" src="https://user-images.githubusercontent.com/13638569/113655208-59472500-96d4-11eb-9a1f-ce7e1e40eb93.png">

**Comment by zcmgyu** [comment]
**Related:**

https://github.com/isaachinman/next-i18next/issues/654

https://github.com/i18next/react-i18next/issues/1291

**Comment by vzaidman** [comment]
can you try importing `useTranslation` from `gatsby-plugin-react-i18next` instead of from `react-i18next`?

**Comment by vzaidman** [comment]
In any case, it's probably related to `gatsby-plugin-react-i18next`.

like @jamuhl wrote in https://github.com/i18next/react-i18next/issues/1291#issuecomment-813844756, the hook `useTranslation` seems to work fine in `react-i18next` (try reproducing the problem without `gatsby` and you would probably not be able to.

**Comment by zcmgyu** [comment]
@vzaidman Thank you for your answer. I attempt to import from both `gatsby-plugin-react-i18next` and `react-i18next` that throws out the same re-render log message on WDYR. In order to avoid the case that you haven't used this library before so I import it directly from `react-i18next` for ease of understanding. 
If it is not a problem that comes from WDYR, I will deep into `gatsby-plugin-react-i18next` and `react-i18next` to find it out. Thanks again 🙇🏻

**Comment by zcmgyu** [comment]
@vzaidman Currently, wdyr did not work with react-scripts v4.0 I tried to figure out the issue all day. LOL.

**Comment by vzaidman** [comment]
There's a workaround for CRA-4 here:
https://github.com/welldone-software/why-did-you-render/issues/154

**Comment by zcmgyu** [comment]
@vzaidman Please downgrade react-scripts in your Code Sandbox. It's actually made newbie misunderstood. Thanks. :bow:

https://codesandbox.io/s/6vowz0w2wz?expanddevtools=1

**Comment by vzaidman** [comment]
Thank you!
I didn't notice I've updated it.

I just fixed it in the sandbox indeed.

**Comment by zcmgyu** [comment]
@vzaidman 
I've already checked it with the non-Gatsby project. The useTranslation hook will not cause any re-render issue while initial.
If I intentionally cause the BigListPureComponent to be re-rendered then I will get the same error as above.
