### ISSUE TITLE
Add option to shorten logs of prev and next

### ISSUE THREAD

**Issue by charles-goode** [welldone-software/why-did-you-render#188]
This library is virtually unusable for me because it will print out huge objects that I have in redux just to say they are in fact the same. That's not helpful to me whatsoever. It fills the entire console and then truncates other useful information. What is the point of printing out the entirety of two objects that are equal by value?? Its not just this repetition, but also that it will print until the console truncates it. This makes me have to spend a ton of time scrolling through to find the useful messages from the library. Its mind numbing. I'm quite surprised no one else has asked for this (or I'm just not good enough at searching to find related issues).

**Comment by vzaidman** [comment]
Yes, the library bloats the console indeed.
I usually only turn the library on when I'm actually debugging performance.
I usually clear the library and then play a certain scenario, to see what would be outputted during the scenario.

**Comment by charles-goode** [comment]
Yeah, I'm definitely not leaving it on, and when I've tried to use it, I always only turn it on for a single component at a time. Even then, its very troublesome. Seems like this could be remedied easily with an option that allows for swapping out the default printDiff function.

**Comment by vzaidman** [comment]
you can create any notifier you want using the option "notifier":
https://github.com/welldone-software/why-did-you-render#notifier
