### ISSUE TITLE
lodash loaded completly and bundle is heavier

### ISSUE THREAD

**Issue by eduardocque** [welldone-software/why-did-you-render#189]
Hi, i found in a few places that we are loading the lodash library completly when this is not required for example

`import { get, isFunction } from 'lodash';`

and should be
`
import get from 'lodash/get';
import isFunction from 'lodash/isFunction';
`

this happen everyplace in the project and for that reason we are adding in the bundle methods that arent used from lodash

for more information please read: https://www.blazemeter.com/blog/the-correct-way-to-import-lodash-libraries-a-benchmark

**Comment by vzaidman** [comment]
the library should only be imported in development anyway, so its bundle size doesn't really matter.

if you import it as:
```
if (process.env.NODE_ENV === 'development') {
  const whyDidYouRender = require('@welldone-software/why-did-you-render');
  whyDidYouRender(React, {
    trackAllPureComponents: true,
  });
}
```
then the library will not be required at all on production.
please check if I'm correct using the bundle analyzer running on prod:
https://www.npmjs.com/package/webpack-bundle-analyzer
