### ISSUE TITLE
Error when inspecting certain Memo component via ReactDevTools

### ISSUE THREAD

**Issue by ljosberinn** [welldone-software/why-did-you-render#20]
As soon as I click [this memoized component](https://github.com/ljosberinn/resources-helper/blob/rhelper4/src/components/HQPlanner/Cell.tsx)

![2019-04-15 11_24_16-DevTools - localhost_3000_hqplanner](https://user-images.githubusercontent.com/29307652/56121727-0917ab00-5f71-11e9-9c78-43c7852859cc.png)

whyDidYouRender crashes while trying to load Hooks:
![2019-04-15 11_28_50-DevTools - localhost_3000_hqplanner](https://user-images.githubusercontent.com/29307652/56121990-a8d53900-5f71-11e9-873f-9eb9ecf8b04a.png)

![2019-04-15 11_22_12-Resources Helper](https://user-images.githubusercontent.com/29307652/56121676-eeddcd00-5f70-11e9-826e-67d7554b98c7.png)
![2019-04-15 11_22_30-DevTools - localhost_3000_](https://user-images.githubusercontent.com/29307652/56121677-eeddcd00-5f70-11e9-8414-c448522a796a.png)

Is this an issue on my side? I don't have this problem with other memoized Hooks-using components, only on this specific one.

**Comment by vzaidman** [comment]
ill fix it shortly

**Comment by htshah** [comment]
I have exact same issue..
Anyone can help us out...

**Comment by vzaidman** [comment]
fixed in v3.0.7
