### ISSUE TITLE
Updated README.md: A fix for wdyr.js not being included on certain webpack config settings

### ISSUE THREAD

**Issue by SantoshKShetty** [welldone-software/why-did-you-render#200]
We can update `Troubleshooting` section with below content in README.md.

* Maybe `webpack's` configuration is causing problems.
    * The `import "./wdyr.js"` statement causes side effects ([more info on MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import#import_a_module_for_its_side_effects_only)).
    If `webpack's`  `optimization.sideEffects` is set to `true` AND your project's `package.json` has `"sideEffects": "false"` (as a measure of performance gain by disallowing inclusion of `side effects` causing files thereby reduce bundle size), then `wdyr.js` doesn't get imported.
    Here's a fix for that:

        We update `wdyr.js` like below:
        ```jsx
        import React from 'react';
        
        export default function wdyr() {
          if (process.env.NODE_ENV === 'development') {
            // Here goes your code.
          }
        }
        ```
        And inside `index.js`:
        ```jsx
        import React from 'react';
        import ReactDOM from 'react-dom';
        import wdyr from './wdyr';
        // ...
        wdyr() // Call this before ReactDOM.render
        // ...
        ReactDOM.render(...);
        ```

**Comment by vzaidman** [comment]
Hey! Thank you for opening the issue!
I can see the problem but the code inside `function wdyr() {` should run before any other file is imported because many libraries create React elements during the initialization of the application.

for example if I have the following in `App.js`:
```jsx
const EMPTY_DIV  = <div/>

export default function App() {
  ...
  ...
   return (
    <div>
      ... 
     {EMPTY_DIV}
   </div>
  );
}
```
your version will fail because `EMPTY_DIV` will be created without the library during the initial import of `App` and then used when the library is already in effect.

in any case, the code inside
```
  if (process.env.NODE_ENV === 'development') {
    // Here goes your code.
  }
```
will be removed in prod so the amount of lines added is minimal.

what do you think?

**Comment by SantoshKShetty** [comment]
Hmm.. I didn't catch what you said at first time @vzaidman , but now I understand :)

So, I studied more into webpack and here: https://webpack.js.org/guides/tree-shaking/, it's said we can provide "sideEffects" an array of side-effect causing imports as well. This is good news because we can selectively tell webpack which side effect causing files we need and let rest skip.

So `wdyr.js` and `index.js` will stay as you told, just in `package.json` we can have `"sideEffects": ["./src/wdyr.js"]`

**Comment by SantoshKShetty** [comment]
We may add this info under troubleshooting section if you feel it has to be.

**Comment by vzaidman** [comment]
I don't really think it's an issue.
