### ISSUE TITLE
Support react-refresh

### ISSUE THREAD

**Issue by gk4m** [welldone-software/why-did-you-render#201]
Does `why-did-you-render` support react-refresh? Currently, I'm trying to setup it in a project where I'm using `react-refresh`  and I'm getting these errors (attached screenshot)

![image](https://user-images.githubusercontent.com/11649967/119844013-5a444800-bf08-11eb-9769-3ded63d9f24b.png)

**Comment by vzaidman** [comment]
Yes, it's suppsoed to be supported.
are you sure `wdyr.js` runs before anything else in the app?

**Comment by gk4m** [comment]
My bad, `wydr.js` was imported in the wrong place. It works now, thanks :)
