### ISSUE TITLE
Tiny typo in codesandbox

### ISSUE THREAD

**Issue by bsides** [welldone-software/why-did-you-render#207]
Just reporting a tiny typo in the official codesandbox example, in the url http://bit.ly/wdyr-sb

TL;DR: Change from `it's` to `its` (bonus: the scaped character goes away too!)

Long version:
Although it looks like nothing, for non native speakers that difference is substantial. If you want a hint on how to remember the usage of `it's` / `its`, change them to `she's` / `her`.

I hope I've helped, thanks for the nice tool!

![image](https://user-images.githubusercontent.com/87631/128601602-282e7684-bd34-45e1-9c43-19314ecc15e0.png)

**Comment by vzaidman** [comment]
Thanks! I've fixed it!
