### ISSUE TITLE
Will this module downside performance on development?

### ISSUE THREAD

**Issue by JounQin** [welldone-software/why-did-you-render#209]
I'm wondering whether should I enable this module always on development? Or should I just enable it when I want to debug some unexpected re-rendering?

```ts
// only uncomment the following line when you want to perf
// import './wdyr'
```

**Comment by vzaidman** [comment]
I think it's better to enable this module if you want to debug perf.

This is because:
* it slows down the app
* it spans the console
* it might cause rare unexpected issues

All of these are not intended when you develop as usual.

**Comment by JounQin** [comment]
Thanks for your reply and suggestion.
