### ISSUE TITLE
Higher-order components from react redux router "withRouter" seem to be ignored

### ISSUE THREAD

**Issue by trevorlang** [welldone-software/why-did-you-render#21]
react@16.8.1
react-router@4.3.1
react-router-dom@4.3.1
react-redux@6.0.0

I am attempting to use `why-did-you-render` to debug some of my route components. The main route container is calling the `Search` component like so:
``` 
...
<Switch>
  <Route exact path="/">
     <Redirect to="/search" />
  </Route>
  <Route path="/search" component={Search} />
  <Route path="/project" component={Project} />
</Switch>
...
```

and the Search component is being exported using the `withRouter` HOC from `react-router-dom` like so:
```
...
export default withRouter(Search)
```

As far as I can tell, it is not currently possible to debug any component that has been wrapped with the `withRouter` HOC.

**Comment by vzaidman** [comment]
how did you use "why did you render" on this component?

i created a sandbox: https://codesandbox.io/s/r59ovw26xp and it works as far as i can see.
play with it to prove me wrong.

it might be a versioning issue, update all your packages and try again.

**Comment by vzaidman** [comment]
If you get this issue, try updating React, React Router, and React Redux
