### ISSUE TITLE
Wydr is causing bug in @react-navigation/bottom-tabs version 5?

### ISSUE THREAD

**Issue by Ayush6543** [welldone-software/why-did-you-render#213]
Whenever I am switching bottom tabs my LogBox gives me a warning saying `Accessing the 'state' property of the 'route' object is not supported. If you want to get the focused route name, use the 'getFocusedRouteNameFromRoute' helper instead:`. But when I uncomment `wydr` import the error resolves. I have posted on StackOverflow about this question too [stackoverflow-question](https://stackoverflow.com/questions/69187743/whenever-i-am-moving-to-different-tab-screens-it-shows-the-error-accessing-the)

**Comment by vzaidman** [comment]
Can you please try again with the latest version of `react-navigation`? I see that they changed the relevant code a little:
https://github.com/react-navigation/react-navigation/commit/ebab5183522f5ae03f50f88289c0e7acc208dc02#diff-ac26dec88d71b31af2479666afdc8aaff2b1c846459c603034bf5b7727184516L40
