### ISSUE TITLE
Use with Recoil hooks?

### ISSUE THREAD

**Issue by kentr** [welldone-software/why-did-you-render#214]
Any ideas on getting this to work with Recoil hooks?

I tried a standard `require()`, and got the error about "only a getter".

```
Cannot set property useSetRecoilState of #<Object> which has only a getter
```

Based on comments in #85, I tried using the `umd` and `cjs` versions of the package. While I don't get the error, I also don't get any of the expected rerender log messages from `why-did-you-render`.

It's a fork of the official Redux example, but with Recoil instead of Redux. So, I expect to see rerenders and corresponding log messages from `why-did-you-render`. 

Here's a [Recoil issue](https://github.com/facebookexperimental/Recoil/issues/41) verifying that complex atoms cause rerenders, and the "BrokenBigPureComponent render!" log message recurs as expected.

Here's the [sandbox](https://codesandbox.io/s/why-did-you-render-4-tracking-of-pure-components-recoil-2x06z?file=/src/App.js).

**Comment by vzaidman** [comment]
You need to ensure you import the library as `cjs` or `umd` across the project and not only for WDYR patching. This will ensure that the same object is used as the one being patched. There's indeed much more info at #85.
