### ISSUE TITLE
This library should provide demo project

### ISSUE THREAD

**Issue by Eliav2** [welldone-software/why-did-you-render#217]
This is quite a popular library and I just can't get it to work, so a demo project could help many of us debug why it does not work in these cases.

**Comment by rosstroha** [comment]
There is a sandbox link in the readme. Is there something more you're looking for? https://codesandbox.io/s/6vowz0w2wz?expanddevtools=1&file=/src/index.js

**Comment by Eliav2** [comment]
but hey, why it doesn't show rerender of not pure components?

**Comment by vzaidman** [comment]
For not pure components, you. need to subscribe manually:
```
Component.whyDidYouRender = true;
```
