### ISSUE TITLE
reword add whyDidYouRender = true to components

### ISSUE THREAD

**Issue by allan-m-bonadio** [welldone-software/why-did-you-render#219]
Hi!  Thanks for writing why-did-you-render, I think it's exactly what we need.  We've been having repeated renders, and now I's my job to fix it.

You've got a piece of the doc that you have to change.  On this page: https://www.npmjs.com/package/@welldone-software/why-did-you-render
You have this sentence:

    Otherwise, add whyDidYouRender = true to components you want to track.

So, after verifying that no messages were coming out, I decided that we don't have any Pure components.  Doesn't surprise me.  So I added whyDidYouRender:

render() {
  …
  return (
      <section
	   whyDidYouRender={true}
        className={ problemContentControllerClassName }
        ref={ (el) => retrieveRootDebugId(this, el) }
      >
…
Well, that didn't work.  Then I thought, no, not on the first subelement, on the component itself.  Unfortunately, this component is the first one in a React portal, so there is no component above (that's easily accessible), so I figured I'd add it as a default prop:

ProblemContentController.propTypes = {
  whyDidYouRender: PropTypes.bool,
…
}
ProblemContentController.defaultProps = {
  whyDidYouRender: true,
	…

Well, that didn't work either.  Finally I read the rest of the page and found this:

class BigList extends React.Component {
  static whyDidYouRender = true

THIS is what you meant!  Could you change that sentence, because it's misleading, and wastes time?

Bad: Otherwise, add whyDidYouRender = true to components you want to track.
Good: Otherwise, add whyDidYouRender = true to your components' class/function object for the components you want to track.

Thanks again!

**Comment by vzaidman** [comment]
Thanks!
