### ISSUE TITLE
browserlist, TypeError: Class constructor "Component" cannot be invoked without 'new'

### ISSUE THREAD

**Issue by frederikhors** [welldone-software/why-did-you-render#24]
`TypeError: Class constructor "Component" cannot be invoked without 'new'`

Using the `create-react-app 3`, `why-did-you-render: v3.0.6` and this import:

`const whyDidYouRender = require('@welldone-software/why-did-you-render/dist/no-classes-transpile/umd/whyDidYouRender.min.js')`

`why-did-you-render: v3.0.6`

My browserlist:

```
  "browserslist": {
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  }
```

**Comment by ljosberinn** [comment]
From what I can tell, this is not related to why-did-you-render at all but a regular javascript TypeError.

**Comment by frederikhors** [comment]
Everything else works good.

**Comment by vzaidman** [comment]
did you try "@welldone-software/why-did-you-render" before?

**Comment by vzaidman** [comment]
what is Navbar?

**Comment by vzaidman** [comment]
create-react-app 3 and wdyr works together:
https://codesandbox.io/s/8ylmw38rl

**Comment by frederikhors** [comment]
After several tests, I finally understood what is happening.

If in my `package.json` I use the new CRA 3 default below:

```json
  "browserslist": {
    "production": [
      ">3%",
      "not dead",
      "not ie <= 11",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  }
```

*deleting before npm start* the `node_modules/.cache` folder it doesn't work!

Re-deleting .cache folder with your below browserlist in package.json it works!


```json
  "browserslist": [
    ">0.2%",
    "not dead",
    "not ie <= 11",
    "not op_mini all"
  ]
```

> did you try "@welldone-software/why-did-you-render" before?

yes of course

**Comment by frederikhors** [comment]
@vzaidman, why did you close? There is still a problem.

**Comment by vzaidman** [comment]
oh i thought you said "it works"

**Comment by vzaidman** [comment]
whats your current browser list? how do you import wdyr? what component are you using it on?

**Comment by vzaidman** [comment]
@frederikhors as far as i know it should work, besides serious issues with browserlist cache that are not related to the project.

please do the following:
* change broserlist and babel config according to your need
* delete `node_modules/.cache`
* re-run

if the issue remains, you are free to reopen this issue and specify:
* your current .browserlistrc
* your babel config
* how do you import wdyr
* how do you use it and on what component
