### ISSUE TITLE
Doesn't work with Vite + React

### ISSUE THREAD

**Issue by Vexcited** [welldone-software/why-did-you-render#243]
Hello ! I'm currently having troubles trying to use this library with my React project.

This is my `wdyr.ts` file:
```javascript
/// <reference types="@welldone-software/why-did-you-render" />
import React from "react";

export default async function load () {
  if (process.env.NODE_ENV === "development") {
    // Importing because we can't require in Vite.
    const { default: whyDidYouRender } = await import("@welldone-software/why-did-you-render");

    whyDidYouRender(React, {
      trackAllPureComponents: true,
    });
  }
}
```

This is how I integrate it in my `main.tsx` (mountpoint)
```javascript
import wdyr from "./wdyr";
await wdyr();

import React from "react";
import ReactDOM from "react-dom";

ReactDOM.render(
  <React.StrictMode>
    <AppRoutingAndMoreRightHere />
  </React.StrictMode>,
  document.getElementById("root")
);
```

When I run it, there isn't any errors, but still it doesn't work.
I've also tried to add `MyComponent.whyDidYouRender = true;` but still have no effect.

By the way, I'm using vite `2.7.13` and react `17.0.2`.

Hope you can help me with this !

**Comment by vzaidman** [comment]
Why is this async?
It won't work because it needs to happen in the first thread of the application. Once you make it async, it moves to the next thread.
Try that and tell me if it helps.

**Comment by Vexcited** [comment]
The thing is that even without async it still doesn't work ~

I made here a StackBlitz example with a blank project.
https://stackblitz.com/edit/vitejs-vite-kyrupm?file=src/main.tsx

See `main.tsx` and `wdyr.ts`.

**Comment by jdnarvaez** [comment]
I was able to get this working with vite by using the following

`wydr.ts`
```javascript
import React from 'react';
import whyDidYouRender from '@welldone-software/why-did-you-render';

if (process.env.NODE_ENV === 'development') {
  whyDidYouRender(React, {
    trackAllPureComponents: true,
  });
}
```

`main.tsx`
```javascript
import './wdyr';
import React from 'react'
.
.
.
```


Then setting `MyFunctionalComponent.whyDidYouRender = true`

**Comment by Vexcited** [comment]
Uhm, I'm sorry but I still can't get it to work with

> main.tsx
```jsx
import './wdyr';
import React from 'react';
import ReactDOM from 'react-dom/client';
import App from './App';
import './index.css';

ReactDOM.createRoot(document.getElementById('root')!).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
);
```

> wdyr.ts
```typescript
/// <reference types="@welldone-software/why-did-you-render" />
import React from 'react';
import whyDidYouRender from '@welldone-software/why-did-you-render';

if (process.env.NODE_ENV === 'development') {
  whyDidYouRender(React, {
    trackAllPureComponents: true,
  });
}
```

```jsx
function App() {
  return (<div>/** some code */</div>);
}

App.whyDidYouRender = true;
export default App;
```

**Comment by jdnarvaez** [comment]
I played around a little bit with your sandbox and I, too, could not get it to work. Might be something with our configs, but what we have setup at my work seems to work with this tool.

**Comment by Vexcited** [comment]
Hope we could find a workaround because I think that this tool can really help me in some of my projects for debugging.

Anyway, I'll try to find more informations on my own about this issue. If I find anything useful, I'll comment it here.

**Comment by jdnarvaez** [comment]
this also seems to work

```javascript
  const { default: whyDidYouRender } = await import('@welldone-software/why-did-you-render');

  whyDidYouRender(React, {
    logOnDifferentValues: true,
    trackAllPureComponents: true,
  });
```

for purposes of keeping it a dev dependency. I am not quite sure why it does not work in the example you posted above.

**Comment by vzaidman** [comment]
@jdnarvaez wait so does it works or not? ;O
> this also seems to work

**Comment by jdnarvaez** [comment]
> @jdnarvaez wait so does it works or not? ;O
> 
> > this also seems to work
> > I would not expect that anything with "await" would work, because it means that the code would be applied in the next browser thread cycle.

It works fine for me in my local project, it does not seem to work on the sandbox that is linked above.

**Comment by Vexcited** [comment]
and also doesn't work in my Vite projects (made with `yarn create vite` and `react-ts` option)

**Comment by anatoliykot** [comment]
Doesn't work for me as well

**Comment by anatoliykot** [comment]
Solution:
vite.config.ts
```
export default defineConfig({
  plugins: [
    checker({ typescript: true }),
    svgr(),
    react({
      jsxImportSource: '@welldone-software/why-did-you-render',
    }),
  ],
  resolve: {
    alias: {
      // Needed for `useSelector` tracking in wdyr.tsx: https://github.com/welldone-software/why-did-you-render/issues/85
      'react-redux': 'react-redux/dist/react-redux.js',
    },
  },
});
```
wdyr.ts
```
/// <reference types="@welldone-software/why-did-you-render" />
import * as React from 'react';
import * as ReactRedux from 'react-redux';
import whyDidYouRender from '@welldone-software/why-did-you-render';

if (import.meta.env.DEV) {
  whyDidYouRender(React, {
    trackAllPureComponents: true,
    trackExtraHooks: [[ReactRedux, 'useSelector']],
  });
}

```

**Comment by Vexcited** [comment]
Sorry for the late response but the solution from @anatoliykot seems to work for me so I'll close this issue !

Thanks you for your help !

**Comment by jensbodal** [comment]
Thanks for proposing a solution, a few questions:


1. `> /// <reference types="@welldone-software/why-did-you-render" />`
  Why do you need to import types like this if you’re already using typescript? 
4. What is the purpose of `jsxImportSource`?  This seems to be working without it. 
5. Where are you importing the `wdyr.ts` file?

**Comment by jensbodal** [comment]
What’s working for me is the following

**wdyr.ts**
```
import * as React from 'react';

if (import.meta.env.DEV && import.meta.env.VITE_ENABLE_WHY_DID_YOU_RENDER === 'true') {
  const { default: wdyr } = await import('@welldone-software/why-did-you-render');

  wdyr(React, {
    include: [/.*/],
    exclude: [/^BrowserRouter/, /^Link/, /^Route/],
    trackHooks: true,
    trackAllPureComponents: true,
  });
}
```

**main.tsx**

```
/* eslint-disable import/first */
// eslint-disable-next-line import/order
import './wdyr';

...

const root = createRoot(container);
root.render( ...
```

**tsconfig.json**
```
    "module": "ES2022",
    "target": "ES2017"
```

Despite using the above module/target browserlist provides a prod build time check to ensure I’m still using compatible features (aka I can’t ship code that’s using top-level await but I _can_ use them behind a dev flag)

No trace of `wdyr` in the build output and works locally with the flag enabled.

**Comment by mwskwong** [comment]
> What’s working for me is the following
> 
> **wdyr.ts**
> 
> ```
> import * as React from 'react';
> 
> if (import.meta.env.DEV && import.meta.env.VITE_ENABLE_WHY_DID_YOU_RENDER === 'true') {
>   const { default: wdyr } = await import('@welldone-software/why-did-you-render');
> 
>   wdyr(React, {
>     include: [/.*/],
>     exclude: [/^BrowserRouter/, /^Link/, /^Route/],
>     trackHooks: true,
>     trackAllPureComponents: true,
>   });
> }
> ```
> 
> **main.tsx**
> 
> ```
> // eslint-disable-next-line import/order
> import './wdyr';
> 
> ...
> 
> const root = createRoot(container);
> root.render( ...
> ```
> 
> **tsconfig.json**
> 
> ```
>     "module": "ES2022",
>     "target": "ES2017"
> ```
> 
> Despite using the above module/target browserlist provides a prod build time check to ensure I’m still using compatible features (aka I can’t ship code that’s using top-level await but I _can_ use them behind a dev flag)
> 
> No trace of `wdyr` in the build output and works locally with the flag enabled.

Why is this marked as a solution? It imports `why-did-you-render` regardless of the environment it is in. It will include `why-did-you-render` in the production bundle.

**Comment by jensbodal** [comment]
> Why is this marked as a solution? It imports `why-did-you-render` regardless of the environment it is in. It will include `why-did-you-render` in the production bundle.

... it does not include it in the production bundle

```
if (import.meta.env.DEV && import.meta.env.VITE_ENABLE_WHY_DID_YOU_RENDER === 'true') {
```

This line is statically analyzed and everything below it is omitted from the production bundle, meaning `why-did-you-render` is not in the production bundle.

This also allows a user to turn it on or off locally by flipping an environment variable for `VITE_ENABLE_WHY_DID_YOU_RENDER`.

This is verified by reviewing the production bundle with and without these flags set.

**Comment by mwskwong** [comment]
> > Why is this marked as a solution? It imports `why-did-you-render` regardless of the environment it is in. It will include `why-did-you-render` in the production bundle.
> 
> ... it does not include it in the production bundle
> 
> ```
> if (import.meta.env.DEV && import.meta.env.VITE_ENABLE_WHY_DID_YOU_RENDER === 'true') {
> ```
> 
> This line is statically analyzed and everything below it is omitted from the production bundle (if the condition is false), meaning `why-did-you-render` is not in the production bundle.
> 
> This also allows a user to turn it on or off locally by flipping an environment variable for `VITE_ENABLE_WHY_DID_YOU_RENDER`.
> 
> This is verified by reviewing the production bundle with and without these flags set, and also verifying the production bundle size is the exact same before and after this change.

Damn, I meant to quote @anatoliykot's post. For his case, it does include that in PROD. And yes, yours doesn't

**Comment by jensbodal** [comment]
Yeah I think the only way around that is to just leave `import './wdyr.ts'` commented out (and not having it use dynamic import) then commenting it back in when you need it.

For just vite+react I saw no difference between the two so I left it as I have it.

**Comment by mwskwong** [comment]
> Yeah I think the only way around that is to just leave `import './wdyr.ts'` commented out (and not having it use dynamic import) then commenting it back in when you need it.
> 
> For just vite+react I saw no difference between the two so I left it as I have it.

I find the safest way is to simply use `require` and tell ESLint to ignore the checking on `wdyr.ts`.

**Comment by vzaidman** [comment]
> import * as React from 'react'; import * as ReactDOM from 'react-dom/client'; import App from './App'; import './index.css';
> 
> ReactDOM.createRoot(document.getElementById('root') as HTMLElement).render( <React.StrictMode> </React.StrictMode> );

where is the WDYR import?

**Comment by gkatsanos** [comment]
None of the proposed solutions worked. If @vzaidman could make it vite-compatible or add a guide on how to get it to work, many of us would be grateful! 🙏

**Comment by gkatsanos** [comment]
> 

this actually worked. 

> What’s working for me is the following
> 
> **wdyr.ts**
> 
> ```
> import * as React from 'react';
> 
> if (import.meta.env.DEV && import.meta.env.VITE_ENABLE_WHY_DID_YOU_RENDER === 'true') {
>   const { default: wdyr } = await import('@welldone-software/why-did-you-render');
> 
>   wdyr(React, {
>     include: [/.*/],
>     exclude: [/^BrowserRouter/, /^Link/, /^Route/],
>     trackHooks: true,
>     trackAllPureComponents: true,
>   });
> }
> ```
> 
> **main.tsx**
> 
> ```
> // eslint-disable-next-line import/order
> import './wdyr';
> 
> ...
> 
> const root = createRoot(container);
> root.render( ...
> ```
> 
> **tsconfig.json**
> 
> ```
>     "module": "ES2022",
>     "target": "ES2017"
> ```
> 
> Despite using the above module/target browserlist provides a prod build time check to ensure I’m still using compatible features (aka I can’t ship code that’s using top-level await but I _can_ use them behind a dev flag)
> 
> No trace of `wdyr` in the build output and works locally with the flag enabled.
