### ISSUE TITLE
Can't get wdyr to work with react > v16

### ISSUE THREAD

**Issue by lrxw** [welldone-software/why-did-you-render#246]
Hi, we tried to get wdyr to work within our application (react 18.1.0). After we failed we had a look on the sandbox examples. The first one (http://bit.ly/wdyr-sb) doesn't work for us (we don't see any wdyr logs) with react 17.x oder 18.x. 
Do we do something wrong? Is that example broken?

**Comment by smckinney1** [comment]
I see the same issue with the sandbox.

Console after clicking "Increase" button with React 17 installed:
<img width="729" alt="Screen Shot 2022-06-03 at 2 11 08 PM" src="https://user-images.githubusercontent.com/13708207/171922087-b98c446b-cc06-4797-b89c-6116a1897b1d.png">

When changing `react` and `react-dom` to version 16.14.0:
<img width="775" alt="Screen Shot 2022-06-03 at 2 10 30 PM" src="https://user-images.githubusercontent.com/13708207/171922003-afc750ac-8cd2-437c-9a6c-c74146f5a040.png">

**Comment by vzaidman** [comment]
@irxw, @smckinney1-
I degraded react to 16.14.0 in the sandbox for time being to ensure it works.
I'm not sure that [codesandbox.io](codesandbox.io) is flexible enough to run with the latest react (unless anybody finds a way) but it's not an issue in this example anyway.
If I'll see a reason to make sure it works with the latest react I'll spend more time on that to ensure it works (if possible).
