### ISSUE TITLE
did not work with react 17/18. 

### ISSUE THREAD

**Issue by zhangenming** [welldone-software/why-did-you-render#249]
https://codesandbox.io/s/why-did-you-render-sandbox-forked-6e451l

Or what's wrong with me?
tks..

**Comment by vzaidman** [comment]
these does not work with how the codesandbox.io implements packages. should work outside of it though.
added the following comment to the sandbox:
   ```
 /**
     * Notice that this sandbox will not work with React 17 or because of how codesandbox.io implements requires.
     */
```

**Comment by zhangenming** [comment]
but my Local PC cant't work too...

**Comment by zhangenming** [comment]
> should work outside of it though. 

NO....it did't

**Comment by vzaidman** [comment]
In what environment?

**Comment by zhangenming** [comment]
vite^2.9.2
"react": "^18.0.0"
Same as sandbox-- no response

**Comment by vzaidman** [comment]
Please see #243 regarding vite.
