### ISSUE TITLE
Export default notifier?

### ISSUE THREAD

**Issue by JoelBrenstrum** [welldone-software/why-did-you-render#25]
I would like to keep the defaultNotifier but extend some of the values, such as displayName with some info from the props, to make it easier to identify the troublesome component.

**Comment by vzaidman** [comment]
great idea. i dont know yet if ill be available to do it, but you are free to open a PR about this.

**Comment by vzaidman** [comment]
published in version 3.0.8

**Comment by vzaidman** [comment]
also see [v3.0.9](https://github.com/welldone-software/why-did-you-render/releases/tag/v3.0.9)
