### ISSUE TITLE
Do the docs explain where to find the WDYR output? 

### ISSUE THREAD

**Issue by jcollum-nutrien** [welldone-software/why-did-you-render#252]
I've got the tool set up and I've been scanning the docs for this question but can't find it. Once WDYR is set up where does it output its analysis? Dev tools? Web server logs? A screenshot of some of the tool's output would be very helpful. 

A coworker actually answered this question. It seems like this should be easy to find in the docs though. I see that it is answered in the Medium article. 

I'd structure it like so: 

- Setup  (how to actually get the tool into your render pipeline) 

- Execution (how to make sure your component under test gets rendered) 
 
- Analysis (where to find and how to read the logs)

**Comment by vzaidman** [comment]
It is outputted to the console.

Thanks for the suggestions! If you come up with better docs, feel free to open a PR- I'll look at it asap.
