### ISSUE TITLE
Objects are equal when saved to the console

### ISSUE THREAD

**Issue by jcollum-nutrien** [welldone-software/why-did-you-render#253]
![image](https://user-images.githubusercontent.com/99687439/186535445-53cbb764-830f-42d0-9ef8-625ce95f280d.png)

Process: 

I was getting output from the tool that told me that the two objects were equal by value but not by ref. OK, so I save them both to globals. But they were equal by ref in that case: `temp1 === temp2 // true` (red line in screenshot) 

But the diffs in the diffs array (which I saved to a global ref from the `diffsAccumulator.push` line while debugging the wdyr code) e.g. `diffs[0].nextValue === diffs[0].prevValue` say the two objects are not equal by ref (green line in screenshot)

The output is confusing if I get different results for equality when accessing the same objects from the console output vs the diffs array. I tried using a stringify (with a replace for circular refs, which could be the issue) and found that the two serialized values were identical. 

This is a confusing result.

**Comment by vzaidman** [comment]
I need more context on this one. What is the tool outputting and what did you save?
Can you please add more info to the screenshot or record a short clip?
