### ISSUE TITLE
Problem: React has detected a change in the order of Hooks called by BrowserRouter

### ISSUE THREAD

**Issue by KirianCaumes** [welldone-software/why-did-you-render#256]
Hello,

I have a problem with `why-did-you-render` and `react-router-dom`.

### Problem

When I use the router and especially a link to change the page, this error is thrown:
```log
Warning: React has detected a change in the order of Hooks called by BrowserRouter. This will lead to bugs and errors if not fixed. For more information, read the Rules of Hooks: https://reactjs.org/link/rules-of-hooks

   Previous render            Next render
   ------------------------------------------------------
1. useRef                     useRef
2. useState                   useState
3. useLayoutEffect            useRef
   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

The problem seems to be inside the [BrowserRouter](https://github.com/remix-run/react-router/blob/6b44e99f0b659428ce2ec8d5098e90c7fddda2c5/packages/react-router-dom/index.tsx#L148) and only appears when the `why-did-you-render` plugin is enable.

I've tried to add/remove React.StrictMode but it doesn't change anything.

### Steps to reproduce

This issue can be reproduced with the starting template from [Vite](https://vitejs.dev/guide/#scaffolding-your-first-vite-project) and the Typescript version.

```tsx
// main.ts
import React from 'react'
import ReactDOM from 'react-dom/client'
import App from './App'
import { BrowserRouter } from "react-router-dom";

ReactDOM.createRoot(document.getElementById('root') as HTMLElement).render(
  <React.StrictMode>
    <BrowserRouter>
      <App />
    </BrowserRouter>
  </React.StrictMode>
);

(await import('@welldone-software/why-did-you-render')).default(React)

// App.ts
import { Link, useRoutes } from 'react-router-dom'

export default function App() {
  const routes = useRoutes([
    { path: "/", element: <>1</> },
    { path: "/2", element: <>2</> },
    { path: "/3", element: <>3</> },
  ])

  return (
    <>
      <Link to="/">1</Link><br />
      <Link to="/2">2</Link><br />
      <Link to="/3">3</Link><br />
      <br />
      {routes}
    </>
  )
}
```

Version of libraries:
- react-dom: v18.2.0
- react-router-dom: 6.3.0
- @welldone-software/why-did-you-render: 7.0.1

I'm not sure what to try to fix or work around this problem, so thanks in advance for your help 🙏

**Comment by bduff9** [comment]
I have the same issue with a brand new Remix project.  This can be seen by running `npx create-remix@latest` and then installing this package.  All client-side routing breaks with the rules of hooks error, though in Remix it's on RemixBrowser.

Here is a sample repo showing the error, just clone, install deps, and run it to see:
https://github.com/bduff9/remix-broken-whydidyourender

**Comment by Waltari10** [comment]
Experiencing similar problem but in react native. Sorry, I don't have steps to reproduce, but this is the stacktrace.
![Simulator Screen Shot - iPhone 14 - 2022-12-01 at 13 27 28](https://user-images.githubusercontent.com/8919286/205042823-9796f086-cf10-4017-bbce-12149e2f7903.png)

**Comment by vzaidman** [comment]
The library will not work if any elements were created before it's loaded so this:
```
(await import('@welldone-software/why-did-you-render')).default(React)
```
is certainly wrong. Find a way to import it not asynchronously.

**Comment by KirianCaumes** [comment]
Solve the problem with this: https://github.com/welldone-software/why-did-you-render/issues/243#issuecomment-1132892461
