### ISSUE TITLE
create-react-app React performance with SVG as ReactComponent and eslint with React.memo missing display name

### ISSUE THREAD

**Issue by frederikhors** [welldone-software/why-did-you-render#26]
I'm using this component in a `create-react-app` app:

```js
import { ReactComponent as ProfileIcon } from "./icons/profile.svg";

...
render(){
  <ProfileIcon {...props}/>
}
```

Using also `why-did-you-render` (https://github.com/welldone-software/why-did-you-render) I got this warning:

```log
SvgProfileIcon
whyDidYouRender.min.js:1191 {SvgProfileIcon: ƒ} "Re-rendered because the props object itself changed but it's values are all equal." "This could of been avoided by making the component pure, or by preventing it's father from re-rendering." "more info at http://bit.ly/wdyr02"
whyDidYouRender.min.js:1191 prev props: {svgRef: null, className: "icon", height: "24", width: "24"} !== {svgRef: null, className: "icon", height: "24", width: "24"} :next props
```

So I made a custom `PureComponent` like this:

```js
import React from "react";

export default WrappedComponent =>
  React.memo(props => <WrappedComponent {...props} />, () => true);
```

**FIRST QUESTION**: Is this performances-correct?

I'm using it like this:

```js
import { ReactComponent as ProfileIcon } from "./icons/profile.svg";

import PureComponent from "./PureComponent";

const PureProfileIcon = PureComponent(ProfileIcon);

...
render(){
  <PureProfileIcon {...props}/>
}
```

**SECOND QUESTION**: Can I avoid this component at all using React.memo (or something else) differently?

Now eslint is complaining about:

```error
Component definition is missing display name eslint(react/display-name)
```

**THIRD QUESTION**: How can I fix this?

**Comment by vzaidman** [comment]
whats the point of
```
React.memo(props => <WrappedComponent {...props} />, () => true);
```
?
it makes it so every props, no metter what, would cause `WrappedComponent` to be recreated.

**Comment by frederikhors** [comment]
Sorry, I don't understand. I'm using `React.memo` to avoid re-render and the second argument is a callback which if true skip the props check.

Am I right?

**Comment by frederikhors** [comment]
I think something like `shouldComponentUpdate() { return false }`.

Am I right?

**Comment by ljosberinn** [comment]
Yes, that's correct, the function passed as 2nd argument to useMemo() is usually called `areEqual`, thus it semantically makes sense to **not** re-render if areEqual returns true.
See https://reactjs.org/docs/react-api.html#reactmemo for reference.

You can fix the eslint/display-name with 
```js
const PureProfileIcon = PureComponent(ProfileIcon);
PureProfileIcon.displayName = 'PureProfileIcon';
```
but that rule is purely [useful during development](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/display-name.md) as production will have names minified anyways so.

**Comment by vzaidman** [comment]
i got it, it means it should never re-render because "areEqual" returns "true"

**Comment by vzaidman** [comment]
for the warning:
"Re-rendered because the props object itself changed but it's values are all equal"
using `React.memo` should be enough:
```
export default WrappedComponent =>
  React.memo(props => <WrappedComponent {...props} />); // no () => true
```
unless you dont want the component to ever re-render. then you indeed can add `() => true` like you did:
```
export default WrappedComponent =>
  React.memo(props => <WrappedComponent {...props} />, () => true);
```

**Comment by frederikhors** [comment]
@vzaidman, @ljosberinn thanks.
