### ISSUE TITLE
What do the colors mean?

### ISSUE THREAD

**Issue by objectiveSee** [welldone-software/why-did-you-render#261]
Do the colors in the terminal here (blue, yellow, green) mean anything? They don't seem to correspond to these colors https://github.com/welldone-software/why-did-you-render#titlecolor--diffnamecolor--diffpathcolor for example, yellow is not defined there. I am happy to update the docs if someone can help me understand this :) 

![Screen Shot 2022-11-22 at 11 42 25 AM](https://user-images.githubusercontent.com/1684106/203395580-a933d5bb-a736-48fa-ab1a-ed57c4bba8a4.png)

**Comment by vzaidman** [comment]
If your terminal re-writes the colours then there's nothing we can do about that. The browser is supposed to show the right colours anyway.

**Comment by objectiveSee** [comment]
But what do the colors mean? Is there any significance to them?

**Comment by vzaidman** [comment]
Nope. Just colours
