### ISSUE TITLE
What to do with react-router?

### ISSUE THREAD

**Issue by frederikhors** [welldone-software/why-did-you-render#27]
Many times I have problem with `<Link ... />` and `<Route ... />` maybe with something like:

```js
<Route
  path={`${match.url}/:player_id`}
  children={props => (
    <PlayerDetail {...props} teamId={match.params.team_id} />
  )}
/>
```

```log
Route
whyDidYouRender.min.js:1185 {Route: ƒ} "Re-rendered because of props changes:"
whyDidYouRender.min.js:1190 props.children
whyDidYouRender.min.js:1190 different functions with the same name.
whyDidYouRender.min.js:1190 {prev children: ƒ} "!==" {next children: ƒ}
```

Can we make a Wiki page (or you have already planned a future article) just for `react-router`?

**Comment by vzaidman** [comment]
how do you use the library?
not every component in your project should not re-render if nothing changed.
when `Route` renders, it indeed receives a new "children" functional component.
what is the question?

**Comment by frederikhors** [comment]
I'll give an example on codesandbox.

**Comment by khaledosman** [comment]
I think the issue is within react-router-dom components themselves, they're not memoized/using PureComponent, I've opened an issue there before https://github.com/ReactTraining/react-router/issues/6434 , so for now there's nothing you can do about it besides ignoring them.

**Comment by jmoyers** [comment]
It seems a lot of very commonly used packages aren't built with memoization in mind. I guess it's fine, premature optimization and all that. Same is true for many things that say they play nicely with hooks, but then return a new function on every call (e.g. react-apollo-hooks).

That being said, what I did with react-router was to, yes, acknowledge that the components behave like that, and 2. use the global exclude feature to reduce noise.

```
whyDidYouRender(React, {
  include: [/.*/],
  exclude: [/^Link/, /^Route/, /^BrowserRouter/]
});
```

**Comment by vzaidman** [comment]
Thats one way to go, but I still think this is not the right way to go. I think we should not usually care about why components render unless they are huge components that are bottlenecks and important to performance
