### ISSUE TITLE
"Support for defaultProps will be removed" error after setting include: [/./] option

### ISSUE THREAD

**Issue by aktasmehmet** [welldone-software/why-did-you-render#286]
In order to work WDYR with Next 13 and AppRouter without a problem, there is a workround (also mentioned here) to put `include: [/./]` to whyDidYouRender function.

When I did that, I started to get strange warnings/errors in the browser console which I never got before:

```
AppRouterAnnouncer: Support for defaultProps will be removed from function components in a future major release. Use JavaScript default parameters instead.

Home: Support for defaultProps will be removed from function components in a future major release. Use JavaScript default parameters instead.

InnerLayoutRouter: Support for defaultProps will be removed from function components in a future major release. Use JavaScript default parameters instead.

...
```
<img width="793" alt="Screenshot 2024-01-05 at 13 46 13" src="https://github.com/welldone-software/why-did-you-render/assets/1397272/bf62f539-e110-49a2-b3b7-bfa3d4ed2e35">

What might be the reason to this? When I remove **include** option, the errors are gone.

**Comment by Xamsix** [comment]
@aktasmehmet I'm experiencing the same issue, did you ever find a workaround?

**Comment by aktasmehmet** [comment]
@Xamsix unfortunately not :( Since this not a blocker issue for me, I kept going but yet I am still waiting for a solution to this.

**Comment by Nilegfx** [comment]
I am facing the same issue. any idea what it is and how can I solve/workaround it?

**Comment by aktasmehmet** [comment]
Still waiting :(

**Comment by Hypnosphi** [comment]
I can publish my fork to provide a temporary workaround

**Comment by Hypnosphi** [comment]
> I can publish my fork to provide a temporary workaround

It's available now as `@hypnosphi/why-did-you-render`

**Comment by Hypnosphi** [comment]
@vzaidman can you please publish 8.0.3 to NPM?

**Comment by vzaidman** [comment]
> @vzaidman can you please publish 8.0.3 to NPM?

@Hypnosphi just did. Sorry for the delay.
