### ISSUE TITLE
Links from the Credits section are broken

### ISSUE THREAD

**Issue by brunocechet** [welldone-software/why-did-you-render#297]
Two of the three links in the credits section are broken. 
Would you mind taking a look?

- https://github.com/maicki/why-did-you-update
- https://benchling.engineering/deep-dive-react-perf-debugging

Currently on master; permanent link [here](https://github.com/welldone-software/why-did-you-render/blob/9d2a9c6cac1ce0dad0fdc4573677362db9e5caa3/README.md#credit).

**Comment by vzaidman** [comment]
fixed! thank you for letting me know!
