### ISSUE TITLE
There was no `forceUpdate`, but getting that as error message

### ISSUE THREAD

**Issue by matthew-dean** [welldone-software/why-did-you-render#3]
I'm seeing lots of:
`Re-rendered although props and state objects are the same. This usually means there was a call to this.forceUpdate() inside the component.`

However, nowhere in those components is there a `forceUpdate()`. So what could that mean?

**Comment by mclngl** [comment]
that's probably related to hot reloading

**Comment by vzaidman** [comment]
I didn't find a way to detect a hot reload rendering yet but we dont track events for 500ms upon a hot reload. this worked nice for me.

**Comment by vzaidman** [comment]
do you receive it for many components?

**Comment by vzaidman** [comment]
try increasing `hotReloadBufferMs` when you patch React:
```js
whyDidYouRender(React, { hotReloadBufferMs: 1500 });
```
https://github.com/welldone-software/why-did-you-render#options

**Comment by matthew-dean** [comment]
@vzaidman I receive it for basically all of my components, I think? And it's on first load, but I can try that.

**Comment by vzaidman** [comment]
@matthew-dean news?

**Comment by vzaidman** [comment]
@matthew-dean news?

**Comment by gabrielmoncea** [comment]
@matthew-dean @mclngl @vzaidman - for me the culprit was `<StrictMode>`

**Comment by vzaidman** [comment]
reopened https://github.com/welldone-software/why-did-you-render/issues/16

**Comment by rpk-red** [comment]
I have same issue. @vzaidman I tried whit `whyDidYouRender(React, { hotReloadBufferMs: 1500 });` but it didn't worked.

**Comment by vzaidman** [comment]
what react version?
using any libraries? mobx maybe?
using React.StrictMode?

**Comment by rpk-red** [comment]
- react: 16.8.3
- Yes, I use a lot of libraries for exp: redux, react-router, redux-orm, redux-thunk, reselect, material-ui... just to name a few.
- No, I'm not using React.StrictMode.

**Comment by vzaidman** [comment]
I can't reproduce it in the many tests the application has including React Redux tests, so i need a more specific scenario to help with it.

**Comment by MBarbone** [comment]
> what react version?
> using any libraries? mobx maybe?
> using React.StrictMode?

is there a particular issue with this and mobx? I am getting the same error and using mobx.

**Comment by vzaidman** [comment]
not that im aware of.
can you attach the component with the problem?

**Comment by vzaidman** [comment]
closed due inactivety

**Comment by ankurkaushal360** [comment]
Just want to point out I get it too but unfortunately can't share the code since it's in a corporate repository.

React Version: 16.13.1
Libraries: N/A, we are using internal React state.
React Strict Mode: No

Apologies for commenting on a closed issue.

**Comment by vzaidman** [comment]
@ankurkaushal360 does it happen in one place or everywhere? can you share at-least some of the relevant code?

**Comment by gempir** [comment]
I just wanted to confirm that for me it was related to using StrictMode
