### ISSUE TITLE
Some react.memo components cause an exception

### ISSUE THREAD

**Issue by JoelBrenstrum** [welldone-software/why-did-you-render#30]
<img width="1027" alt="Screen Shot 2019-05-07 at 10 44 48 AM" src="https://user-images.githubusercontent.com/4349208/57260507-0ca5da00-70b8-11e9-9438-44704eced992.png">
<img width="401" alt="Screen Shot 2019-05-07 at 10 43 09 AM" src="https://user-images.githubusercontent.com/4349208/57260516-0f083400-70b8-11e9-923c-61e69112a9ff.png">

**Comment by JoelBrenstrum** [comment]
#29

**Comment by JoelBrenstrum** [comment]
<img width="1090" alt="Screen Shot 2019-05-08 at 10 53 14 AM" src="https://user-images.githubusercontent.com/4349208/57337964-abe1d480-717f-11e9-93f8-b7bd8db5e585.png">

**Comment by vzaidman** [comment]
oh so it also has to do with #27

**Comment by vzaidman** [comment]
actually maybe #21

**Comment by vzaidman** [comment]
how `withRouter` was used on this component?

**Comment by vzaidman** [comment]
any idea how can i reproduce it in my sandbox?
https://codesandbox.io/s/r59ovw26xp

**Comment by vzaidman** [comment]
If you get this issue, try updating React, React Router, and React Redux

**Comment by vzaidman** [comment]
A fix to this might also be live on version 3.1.0
