### ISSUE TITLE
Deprecating the library

### ISSUE THREAD

**Issue by vzaidman** [welldone-software/why-did-you-render#302]

**Comment by jkoutavas** [comment]
Oh?

**Comment by jbanovs** [comment]
@vzaidman Hello! Could you please explain the motivation behind creating this issue? It would be very helpful. 

Recently, we've had many discussions about whether we really need memoization and when to use it. We've also debated when re-renders should be considered problematic. 

It seems that React is efficient enough now on its own, and the React team suggests not to overly focus on preventing re-renders or memoize everything unless there's an obvious performance issue in the application.

What do you think?

**Comment by vzaidman** [comment]
I had a blocker in making the library work with React 19 so I was planning to deprecate the library, however I found a way to fix it, so I'm closing the issue for now.
