### ISSUE TITLE
[Question] ability to add to all components?

### ISSUE THREAD

**Issue by justinhelmer** [welldone-software/why-did-you-render#32]
First, thanks for such an amazing tool with hooks support. Incredibly helpful.

We have over 100 components in our project, and it will take a long time to manually add `Component.whyDidYouRender = true;` in every single file.

Is there a way to attach to everything? I see the `[include]` option, but we are currently not using `DisplayName` - so we would still have to touch every file.

Thanks for the help.

**Comment by vzaidman** [comment]
what would you like to use to decide if a component should be tracked?

https://github.com/welldone-software/why-did-you-render/blob/master/src/shouldTrack.js

here is the file that makes this decision

**Comment by justinhelmer** [comment]
Thanks for the quick reply. I suppose I'm suggesting something along these lines:

```js
return !!(
    options.includeAll ||
    Component.whyDidYouRender ||
    shouldInclude(displayName, options)
  )
```

**Comment by vzaidman** [comment]
try `include: [/.*/]`.

what do you say?

**Comment by justinhelmer** [comment]
works like a charm, thanks.

Now we are just trying to figure out a clever way to not include this with our production bundle, since the build process will include the file in the final bundle regardless of NODE_ENV

**Comment by justinhelmer** [comment]
Feel free to close this issue

**Comment by zhangenming** [comment]
so why not provide a option?
such as 
```js
const whyDidYouRender = require('@welldone-software/why-did-you-render')
whyDidYouRender.isTrackAllPureComponent = true //default can be false
whyDidYouRender(React)
```

**Comment by vzaidman** [comment]
i don't want people to track all components. it's not a best practice.
if you want to do it, use `include: [/.*/]`

**Comment by vzaidman** [comment]
that's a good idea. ill consider it

**Comment by vzaidman** [comment]
implement SCU?

**Comment by zhangenming** [comment]
scu: shouldComponentUpdate

**Comment by vzaidman** [comment]
ok ill add this configuration. thanks for the idea
