### ISSUE TITLE
Recompose "Pure" wipes logs

### ISSUE THREAD

**Issue by lkostrowski** [welldone-software/why-did-you-render#35]
Hi

I used this lib and its great. So I started to fixing my rerending problems. I added Recompose's `Pure()` HOC to check how it goes. My rerenders still occur, but the logs are missing.

**Comment by vzaidman** [comment]
Hey! I'm glad you like it.

Try using
```
Component.whyDidYouRender = {
  logOnDifferentValues: true,
}
```
To have a log of all renders even if they are "justifyeble". this might help you.

**Comment by lkostrowski** [comment]
I added, but its also wiped...
Does it look like something which can make a conflict?

https://github.com/acdlite/recompose/blob/master/src/packages/recompose/pure.js

**Comment by vzaidman** [comment]
can you try to recreate the scenario in www.codesandbox.com?

**Comment by lkostrowski** [comment]
Sorry, I cant, it's very complex component with ton of HOCs... Anyway if you don't see anything, thanks for help - I will check on my own

**Comment by vzaidman** [comment]
recompose is supported. i use it everywhere myself

**Comment by lkostrowski** [comment]
Ok, so I will dig deeper
