### ISSUE TITLE
Functions in useContext API

### ISSUE THREAD

**Issue by Schiavi** [welldone-software/why-did-you-render#36]
Hello,

I have a Context API component to show/hide a modal. I'm using something very similar to the Toast example from here: [Ponyfoo Toast](https://ponyfoo.com/articles/discovering-patterns-with-react-hooks)

WDYR gives me this error:
![Captura de Tela 2019-06-03 às 10 39 51](https://user-images.githubusercontent.com/13576166/58806439-9039e480-85ec-11e9-8af9-17e3dfc27a25.png)

How can I avoid this re-render? Or it is normal react behavior?

All functions are created using useCallback, I've already tried adding memo to both the `<Header />`(the component that I tested WDYR) and the `<Context.Provider />`

Any ideas?

Thanks in advance

**Comment by vzaidman** [comment]
a hook makes components re-render "from the inside" of the component, so MEMO won't help.

what you need to do is to ensure, what ever passes
```
{hideAddressModal, showAddressModal}
```
is memoized.
For example, wrap it in a Memoized component.

**Comment by Schiavi** [comment]
@vzaidman Thank you for your answer.

I've created a very simple CRA app to show how I'm doing it. My context already has a memo around it, and even still, it re-renders the `<Header>` every time.

[Here is the repo](https://github.com/Schiavi/context-memo)

Any suggestions on what I'm doing wrong?

Thanks again.

**Comment by vzaidman** [comment]
ok so here
```
const ModalManager = ({ children }) => {
  const { show, hideModal, showModal } = useModalManager();

  return (
    <ModalContext.Provider value={{ showModal, hideModal }}>
      {children}
      {show && <Modal onDismiss={hideModal} />}
    </ModalContext.Provider>
  );
};
```
`{ showModal, hideModal }` is a new object on every `ModalManager` re-render that triggers a re-render of every children that uses `ModalContext`

what i suggest you to do is something like:
```
const useModalManager = () => {
  const [show, setShow] = useState(false);

  const showModal = useCallback(() => {
    setShow(true);
  }, []);

  const hideModal = useCallback(() => {
    setShow(false);
  }, []);

  const actions = useMemo(() => ({
    showModal, hideModal
  }), [])

  return {
    show,
    actions,
  };
};
```
and then:
```
const ModalManager = ({ children }) => {
  const { show, actions } = useModalManager();

  return (
    <ModalContext.Provider value={actions}>
      {children}
      {show && <Modal onDismiss={actions.hideModal} />}
    </ModalContext.Provider>
  );
};
```
I didnt run it but i think you'll get the idea behind it.

the main point is to make sure value is always exactly the same object and not a new one on every `ModalManager` re-render

**Comment by Schiavi** [comment]
@vzaidman That worked like a charm! Thank you very much. =)

**Comment by vzaidman** [comment]
Sure :)

**Comment by shahafa** [comment]
IMHO I think it is better to put the useMemo outside of the hook in ModalManager since it's not related to the hook logic and more robust

`
const useModalManager = () => {
  const [show, setShow] = useState(false);

  const showModal = useCallback(() => {
    setShow(true);
  }, []);

  const hideModal = useCallback(() => {
    setShow(false);
  }, []);

  return {
    show,
    showModel,
    hideModel
  };
};
`

`
const ModalManager = ({ children }) => {
  const { show, showModel, hideModel } = useModalManager();

  const actions = useMemo(() => ({
    showModal, hideModal
   }), [showModal, hideModal])
  
  return (
    <ModalContext.Provider value={actions}>
      {children}
      {show && <Modal onDismiss={hideModal} />}
    </ModalContext.Provider>
  );
};
`
