### ISSUE TITLE
react-i18next re-render

### ISSUE THREAD

**Issue by gabrielmoncea** [welldone-software/why-did-you-render#37]
It seems that "react-i18next" triggers a re-render of the component.
What step do you think is the best course of action?

<img width="651" alt="Screenshot 2019-06-06 at 01 10 24" src="https://user-images.githubusercontent.com/39256258/58996395-4faeb680-87f8-11e9-92b8-8ae050ebc2e8.png">

**Comment by gabrielmoncea** [comment]
My bad. I just had to be more careful when using it. Congratulations for what you have built! This library is super! 🥇

**Comment by tkdaj** [comment]
Can you elaborate on what you did to use the library more carefully? I'm having a similar issue on all of my translated components.

**Comment by gabrielmoncea** [comment]
@tkdaj it was 4 months ago. I don't remember. Can you give me a snippet so I compare it with what I have?

**Comment by tkdaj** [comment]
<p>
    {this.props.t(`translation.key`)}
</p>

...

export default translate('translations')(MyComponent);

this is essentially how I am using it everywhere.

**Comment by vzaidman** [comment]
I use it with the newly released hook:
https://react.i18next.com/latest/usetranslation-hook

btw, make sure to upgrade all the related libraries (React, react-i18next, wdyr).

**Comment by tkdaj** [comment]
I haven't upgraded to 16.8 yet, so I can't use hooks yet. We're looking at upgrading right now, though, so I will keep this in mind when we do.  Thank you!

**Comment by vzaidman** [comment]
Ok. the library does not guarantee it would work for older versions. I'm upgrading it to work with React 16.10.1 right now.
