### ISSUE TITLE
A why-did-you-render devtool addon

### ISSUE THREAD

**Issue by adberard** [welldone-software/why-did-you-render#38]
Someone posted this on reddit :
https://www.reddit.com/r/reactjs/comments/byl39e/new_devtools_profiler_answers_the_question_why/

I thouhgt that maybe you two could have a talk.

**Comment by vzaidman** [comment]
Thanks we scheduled a meeting already :)

**Comment by vzaidman** [comment]
In short the difference between the "devtool addon" and this library is the library operates in "push mode" where as the addon operates in "pull mode":
* _push mode_: you mark "huge" components with `whyDidYouRender = true` and proceed to work on your stuff. after some time suddenly you get notifications about the huge component being re-rendered.
* _pull mode_: you *intentionally* investigate performance issues and intentionally want to check why a specific component is re-rendered.
