### ISSUE TITLE
TypeError: Cannot read property '_prevProps' of undefined

### ISSUE THREAD

**Issue by rosskevin** [welldone-software/why-did-you-render#4]
I'm trying to start wide then narrow it down - I have a large set of components involved in a complex form and going component by component at this point to turn on would be painful.  I see Consumer and Provider types are failing with the `cannot be invoked without 'new'` error, no problem anyway, I am not interested in them.  But I get to a point where I have no info on what to ignore to continue.

```ts
if (process.env.NODE_ENV === 'development') {
  const whyDidYouRender = require('@welldone-software/why-did-you-render')
  whyDidYouRender(React, {
    exclude: [/Consumer|Provider|AutoSignout/],
    include: [/^.*/],
  })
}
```

```
whyDidYouRender.min.js:8 Uncaught (in promise) TypeError: Cannot read property '_prevProps' of undefined
    at value (whyDidYouRender.min.js:8)
    at f.o.render (whyDidYouRender.min.js:8)
    at createElements.js:38
```

Any thoughts on determining the offending displayName here?

**Comment by rosskevin** [comment]
I manually removed the  `.min` from the package.json bundles so I could traverse the code more easily.  Looks like related to loadable-components or `Route`...not sure, but I'm continuing to narrow it down now.

**Comment by vzaidman** [comment]
add
```
if (!this) {
  debugger;
}
```
to the render FN:
```
render(){
if (!this) {
  debugger;
}
      if(this._prevProps){
        options.notifier(getUpdateInfo({
          Component: ClassComponent,
          displayName,
          prevProps: this._prevProps,
          prevState: this._prevState,
          nextProps: this.props,
          nextState: this.state,
          options
        }))
      }

      this._prevProps = this.props
      this._prevState = this.state

      return super.render && super.render()
    }
```
