### ISSUE TITLE
Does this lib has debugger?

### ISSUE THREAD

**Issue by meetromb** [welldone-software/why-did-you-render#44]
**React** ver: 16.8.6
**why-did-you-render** ver: 3.2.1

No any output in console. How I can check if the library is working?

**Setup code:**
`import whyDidYouRender from '@welldone-software/why-did-you-render'`
`whyDidYouRender(React)`

<img width="450" alt="Снимок экрана 2019-07-03 в 16 57 24" src="https://user-images.githubusercontent.com/34175623/60597469-a980ad00-9db3-11e9-903c-0dc1325ce217.png">

**Component code:**
<img width="302" alt="Снимок экрана 2019-07-03 в 16 58 17" src="https://user-images.githubusercontent.com/34175623/60597537-c3ba8b00-9db3-11e9-8bdf-77ce05979303.png">

**Comment by vzaidman** [comment]
run this code twice:
![image](https://user-images.githubusercontent.com/5188459/60600379-b5bb3900-9db8-11e9-8e2d-529598c33f17.png)
![image](https://user-images.githubusercontent.com/5188459/60600383-b6ec6600-9db8-11e9-9ef2-337c0e3546ab.png)

**Comment by meetromb** [comment]
Thanks!)
