### ISSUE TITLE
"different functions with the same name", but I'm using useCallback.

### ISSUE THREAD

**Issue by DaleSalcedo** [welldone-software/why-did-you-render#46]
I've tried posting this on StackOverflow with no response was hoping to get some more detail here.  I recreated a very simple project to replicate what's going on in a bigger project of mine.  https://github.com/DaleSalcedo/PropFunctionProblem.  In my App.js I'm passing down this function:

```
const modifyPlayer = React.useCallback((playerId, propertyName, value) => {
    const playerCopy = {...playerDict[playerId]};
    playerCopy[propertyName] = value;
    const playerDictCopy = {
      ...playerDict,
      [playerId]: playerCopy
    };
    setPlayerDict(playerDictCopy);  // useState function
  }
  ,[playerDict]);
```

I pass that down 2 components as props and use it here:

```
export const Player = ({player, modifyPlayer}) => {
  const handleOnChange = React.useCallback((event) => {
    modifyPlayer(player.id, event.target.name, event.target.value);
  }, [player, modifyPlayer]);

  return (
    <div>
      <input type={"text"} name={"firstName"} value={player.firstName} onChange={handleOnChange}/>
      <input type={"text"} name={"lastName"} value={player.lastName} onChange={handleOnChange}/>
    </div>
  );
};
```

I'm not sure why it's giving me that message "different functions with the same name" for "modifyPlayer" function when I used "useCallback".

Is this a bug or can someone explain what's going on?

**Comment by vzaidman** [comment]
This comparison was created before hooks were available, where passing `() =>` to big components meant trouble. Now it's not the vase however:
`useCallback` regenerates the fn passed to a component only if it changed.

It's indeed something that we need to rethink.

**Comment by vzaidman** [comment]
after investigating this issue I believe I have the answers.

When you mark a "huge" component with "whyDidYouRender", you expect it to not re-render where it can be prevented.

While `React.useCallback` is a very useful hook, it might cause problems nevertheless.

For example (i created a sandbox for this):
https://codesandbox.io/s/welldone-softwarewhy-did-you-render-usecallback-example-7co06

```
const UseCallbackNewFnOnClick = () => {
  const [value, setValue] = React.useState(0);

  // this useCallback returns a new function on each value change
  const handleClick = React.useCallback(() => {
    setValue(value + 1);
  }, [value, setValue]);

  return (
    <div>
      <h1>useCallback</h1>
      value: {value}
      <br />
      <HugeComponentWithButtonWeDontWantToReRender
        text="increase"
        onClick={handleClick}
      />
    </div>
  );
};
```
vs
```
const UseCallbackAlwaysSameFn = () => {
  const [value, setValue] = React.useState(0);

  // this useCallback never returns a new function
  const handleClick = React.useCallback(() => {
    setValue(value => value + 1);
  }, [setValue]);

  return (
    <div>
      <h1>useCallback</h1>
      value: {value}
      <br />
      <HugeComponentWithButtonWeDontWantToReRender
        text="increase"
        onClick={handleClick}
      />
    </div>
  );
};
```
If you mark a component with `whyDidYouRender`, it probably means you don't want it to receive a new fn all the time. this can be prevented in many ways. one of them is the way displayed in the example, another one would be not to use hooks at all.

what do you think @DaleSalcedo ?

**Comment by Hypnosphi** [comment]
Related: https://github.com/facebook/react/issues/14099

**Comment by vzaidman** [comment]
> Related: [facebook/react#14099](https://github.com/facebook/react/issues/14099)

exectly

**Comment by Hypnosphi** [comment]
Possible workararound: https://github.com/facebook/react/issues/14099#issuecomment-440013892

```js
// use this instead of `useEffect`
function useEventCallback(fn) {
  let ref = useRef();
  useEffect(() => {
    ref.current = fn;
  });
  return useCallback((...args) => (0, ref.current)(...args), []);
}
```

**Comment by DaleSalcedo** [comment]
@vzaidman yes that makes alot of sense.  thank you for the example as well.  

i should probably close this issue now, thanks everyone for the feedback!

**Comment by Hypnosphi** [comment]
@vzaidman there are valid cases for callback invalidation, see https://github.com/facebook/react/issues/14099#issuecomment-541714637

How can I tell `why-did-you-render` that callback reference change is expected here?

**Comment by vzaidman** [comment]
yes there are. I still think about how to make it as clear and as robust as possible in this sense. if you have any suggestions, i'll be glad to hear.

**Comment by vzaidman** [comment]
Re-opened for the record because I was asked about it again:

We wait on https://github.com/facebook/react/issues/14099 to be fixed so the fn returned from `useCallback` wan't cause a re-render of the component it is passed to.

**Comment by vzaidman** [comment]
fixed in https://github.com/welldone-software/why-did-you-render/releases/tag/v5.0.0-alpha.2
