### ISSUE TITLE
Error: Cannot read property 'displayName' of undefined

### ISSUE THREAD

**Issue by Zodiase** [welldone-software/why-did-you-render#47]
I'm using `styled-components`. The error happens with something like this:

```JavaScript
const FooBar = memo(() => <div>foobar</div>);
const StyledFooBar = styled(FooBar)``;

StyledFooBar.whyDidYouRender = true;
```

![image](https://user-images.githubusercontent.com/1815174/60948906-e0b9f700-a2a8-11e9-907a-a43888f376fd.png)

**Comment by vzaidman** [comment]
fixed in [v3.3.1](https://github.com/welldone-software/why-did-you-render/releases/tag/v3.3.1)
