### ISSUE TITLE
React Native 0.60.5 fails to launch and memory goes through the roof

### ISSUE THREAD

**Issue by robertherber** [welldone-software/why-did-you-render#55]
Seems like this library works when running React Native but _only_ when the debugger is attached - which I think implies it has to do with the JavaScript engine (when attaching the debugger it runs V8). It goes for both iOS and Android - on the device and simulator.

It launches the app - succeeds in running decent amounts of JavaScript code i can tell from the logs - but fails to render. Memory consumption goes through the roof during this process as well (after about a minute my app was consuming almost 10gb of memory).

It doesn't render the library completely unusable with RN but it bugs me to have to manually comment the whole library out when I want to run it without an attached debugger - which is usually the case since it has some heavy performance implications.

**Comment by robertherber** [comment]
I found a workaround that I'll use for now. There is global to determine whether RN is running in the Chrome Debugger `global.__RCTProfileIsProfiling`, so I'm disabling it otherwise:
```javascript
if (__DEV__ && global.__RCTProfileIsProfiling) {
    const whyDidYouRender = require('@welldone-software/why-did-you-render');
    whyDidYouRender(React);
}
```

**Comment by codecog** [comment]
Experiencing the same issue. Works fine on first load but after fast refresh tries to kick in the app memory usage goes 1000mb+ and the simulator has to be force closed.

**Comment by vzaidman** [comment]
re-open if it still happens
