### ISSUE TITLE
Doesn't show anything in console

### ISSUE THREAD

**Issue by HugoLiconV** [welldone-software/why-did-you-render#57]
I don't know what I'm doing wrong, but nothing is shown in the console.

This is how I set it up: 
I execute `whyDidYouRender` in `index.tsx` like this:
```javascript
if (process.env.NODE_ENV !== 'production') {
  const whyDidYouRender = require('@welldone-software/why-did-you-render');
  whyDidYouRender(React);
}

ReactDOM.render(<App />, document.getElementById('root'));
```
And I added the static property `whyDidYouRender` to App.tsx
`App.whyDidYouRender = true;`

I don't know if I missing something

**Comment by mikalai-sauchanka** [comment]
I have same issue. I used "why-did-you-update" before, but it stopped working.
Is there a "debug" mode to troubleshoot?

**Comment by vzaidman** [comment]
probably app just doest re-render without a reason.
try to see if this triggers logs
```
ReactDOM.render(<App />, document.getElementById('root'));
ReactDOM.render(<App />, document.getElementById('root'));
```

**Comment by mikalai-sauchanka** [comment]
OK. In my case it was a typescript setting in tsconfig.json. Changed "module" from "commonjs" to "ES6"...

**Comment by vzaidman** [comment]
great!

**Comment by HugoLiconV** [comment]
> probably app just doest re-render without a reason.
> try to see if this triggers logs
> 
> ```
> ReactDOM.render(<App />, document.getElementById('root'));
> ReactDOM.render(<App />, document.getElementById('root'));
> ```

this worked for me, thanks!

**Comment by vzaidman** [comment]
I guess you might benefit from reading about the library and what it concederes "redundant re-renders" here:
http://bit.ly/wdyr1
