### ISSUE TITLE
Scala.Js compatibility

### ISSUE THREAD

**Issue by evbo** [welldone-software/why-did-you-render#61]
Hi, this might be outside the scope of your intended use-cases, but I'm trying to transcompile javascript using ScalaJs and was wondering if you might be able to advise on an error I'm getting when using why-did-you-render in my React 16.8.4 application:

```
react-dom.development.js?4646:20312 Uncaught TypeError: t.include.some is not a function
    at eval (_freeGlobal.js?7bdd:2)
    at ro (_freeGlobal.js?7bdd:2)
    at ko (_freeGlobal.js?7bdd:2)
    at Object.eval [as useState] (_freeGlobal.js?7bdd:2)
    at Object.useState (react.development.js?9c48:1462)
    at client-fastopt.js:27081
    at $c_sjsr_AnonFunction1.apply__O__O (client-fastopt.js:25930)
```

Here is relevant info from errorInfo object that gets printed when tries to work on my `main` functional component:

```javascript
displayName: "main "
options: include: ƒ (arg1) {
arguments: [Exception: TypeError: 'caller', 'callee', and 'arguments' properties may not be accessed on strict mode functions or the arguments objects for calls to them at Function.remoteFunction (<anonymous>:2:14)]
caller: [Exception: TypeError: 'caller', 'callee', and 'arguments' properties may not be accessed on strict mode functions or the arguments objects for calls to them at Function.remoteFunction (<anonymous>:2:14)]
length:1
name:""
}
```

I am calling why-did-you-render with `include: /.*/` to avoid polluting my code as described in the docs.

**Comment by vzaidman** [comment]
does it happens when you dont use the library? did you try updating React?

* note: I do not suggest using the library on ALL components. Better use it only huge components that you want to make sure are not re-rendered when they do not need to.

**Comment by evbo** [comment]
no, my app runs fine without it and I updated to React `16.8.6` and still it occurs. I can't update beyond that because I have class-based components that are deprecated and I haven't gotten around to that refactor yet.

I'm using `.*` simply to get _something_ working. I've tried `/^main` instead and still get same error.

**Comment by evbo** [comment]
@vzaidman thank you, I think I have it working now! It was an issue on the scala side.
