### ISSUE TITLE
Gatsby integration

### ISSUE THREAD

**Issue by gabrielmoncea** [welldone-software/why-did-you-render#63]
Did anyone manage to integrate this library with Gatsby?

**Comment by JustFly1984** [comment]
I’m also interested to integrate this library

**Comment by gabrielmoncea** [comment]
@JustFly1984 do you want to work on this together? I tried contacting the Gatsby team to get some guidance but no one answered

**Comment by vzaidman** [comment]
I don't have experience with getsby but i'd be happy to answer your questions in this tread

**Comment by gabrielmoncea** [comment]
I was writing my questing to you and then I realised I had the wrong thought all along. Just to clarify, where should your library be initiated?

In the README it just says to:
```
import React from 'react';

if (process.env.NODE_ENV !== 'production') {
  const whyDidYouRender = require('@welldone-software/why-did-you-render');
  whyDidYouRender(React);
}
```

But it doesn't say anything. Until now, I always did it as the first thing in App.js

**Comment by vzaidman** [comment]
it is. and later you add it on components to make sure they don't receive redundant re-rendereds

```
App.whyDidYouRender = true
```

**Comment by gabrielmoncea** [comment]
@vzaidman I edited my last comment

**Comment by vzaidman** [comment]
it's best to initiate it before anything happens regarding React. (usually in index.js) or

**Comment by vzaidman** [comment]
what exactly is the problem?
I suspect gatsby executes code before you get to App. this is why in next.js for example I used to do the following to make sure `whyDidYouRender` runs first. (simplified) (also it's not needed anymore on newest versions):
```
    if (dev && !isServer) {
      webpackConfig.entries['main.js'].unshift('./common/whyDidYouRender.js');
    }
```
where `common/whyDidYouRender.js` was:
```
import React from 'react';
import whyDidYouRender from '@welldone-software/why-did-you-render';

whyDidYouRender(React);
```

**Comment by JustFly1984** [comment]
@vzaidman 
Well, gatsby.js has `gatsby-browser.js` api where we can execute `whyDidYouRender(React)` but it has different approach to webpack config, and it is not obvious how to change it, if it needs to be changed at all.

**Comment by vzaidman** [comment]
yes. the webpack is not the point. the point is to make sure no React components are mounted before whyDidYouRender is executed (`whyDidYouRender(React);`)

**Comment by vzaidman** [comment]
oh, and also, don't let `whyDidYouRender(React);` run on gatsby server side. it would just slow it. make it only run on dev, on browser.

**Comment by universse** [comment]
Gatsby's browser API [onClientEntry](https://www.gatsbyjs.org/docs/browser-apis/#onClientEntry) is perfect for this.

```js
// gatsby-browser.js
import React from 'react'

export const onClientEntry = () => {
  if (process.env.NODE_ENV !== 'production') {
    const whyDidYouRender = require('@welldone-software/why-did-you-render')
    whyDidYouRender(React)
}
```

I would be open to making a plugin for this too.

**Comment by vzaidman** [comment]
Sure. if you open, i'll link to it from the README

**Comment by gabrielmoncea** [comment]
@universse I tried your suggestion with an anonymous functions but it's not working.

**Comment by universse** [comment]
Can you please share your code for gatsby-browser? It seems to be working fine on my end.

**Comment by gabrielmoncea** [comment]
@universse I just copy-pasted your code and than set `whyDidYouRender = true` on one of the components

**Comment by universse** [comment]
In what way is it not working? Is there any error message? Where did you put the above code?

![image](https://user-images.githubusercontent.com/15166715/67175338-49605600-f3f8-11e9-8ab1-ab1a67047ecf.png)

**Comment by gabrielmoncea** [comment]
@universse  I started a new project from scratch. I might be missing something that I don't see.

This is my index.js
```
import React from "react"
import { Link } from "gatsby"

import Layout from "../components/layout"
import Image from "../components/image"
import SEO from "../components/seo"
import TestComponent from "../components/TestComponent"

const IndexPage = () => {
  const [text, setText] = React.useState('')
  return (
    <Layout>
      <SEO title="Home" />
      <h1>Hi people</h1>
      <p>Welcome to your new Gatsby site.</p>
      <p>Now go build something great.</p>
      <div style={{ maxWidth: `300px`, marginBottom: `1.45rem` }}>
        <Image />
      </div>
      <input type="text" value={text} onChange={({ target: { value } }) => { setText(value) }} />
      <TestComponent text={text} />
      <Link to="/page-2/">Go to page 2</Link>
    </Layout>
  )
}

IndexPage.whyDidYouRender = true

export default IndexPage
```

And this is my TestComponent.js
```
import React from 'react'

const TestComponent = ({ text }) => (
  <div>{text}</div>
)

TestComponent.whyDidYouRender = true
export default TestComponent
```

**Comment by universse** [comment]
Doesn't props `texts` always change when you type? So in this case re-rendering is expected.

Anw here's an example sandbox. https://codesandbox.io/s/gatsby-starter-default-swdwx

The example site is https://swdwx.sse.codesandbox.io/. You can try open the console and type into the input box.

**Comment by gabrielmoncea** [comment]
@universse @vzaidman - I've managed to make it work but it's really confusing and here's why:

1. It doesn't work if you try it on the whole page component like `IndexPage.whyDidYouRender = true` . I think this was expected but I've missed it.

2. Second of all, if I add `text` prop value to TestComponent it stops working, no matter where I set `whyDidYouRender = true`. It works only if TestComponent has no prop set

I'm not sure why this happens. Do you have any idea?

**Comment by vzaidman** [comment]
whyDidYouRender tracks re-renders that are caused by **unexpected** reasons.
if a prop changes, you **do** expect a re-render.
try adding the prop `p={[]}` for example to a component set to track unexpected changes.
it would cause the component re-render even if it's pure because `[] !== []`.

**Comment by universse** [comment]
You can use `logOnDifferentValues` option to enable additional logging, even when re-render is expected.

```js
TestComponent.whyDidYouRender = {
  logOnDifferentValues: true
}
```

**Comment by gabrielmoncea** [comment]
Thank you!

**Comment by vzaidman** [comment]
Your comments are very valuable. I'll try to find a way to make it more intuitive in the future.

**Comment by jasonwilliams** [comment]
> this is why in next.js for example I used to do the following to make sure `whyDidYouRender` runs first. (simplified) (also it's not needed anymore on newest versions):

@vzaidman how do you use it on new versions?
