### ISSUE TITLE
3RD party debugging(Reactotron via realm.js edition)

### ISSUE THREAD

**Issue by Genhain** [welldone-software/why-did-you-render#65]
I recently made the pull request for #64 and it was not out of philanthropy and more necessity.
I am on React Native using [realm.js](https://github.com/realm/realm-js) and anyone who has tried using realm on React Native knows [that it has some issues](https://github.com/realm/realm-js/issues/491).

After browsing solutions in the issues of Realm, you will come across people mentioning [Reactotron](https://github.com/infinitered/reactotron). It works wonderfully with a few tweaks.

The issue is that the Reactotron is, it does not seem to have an equivalent function of `console.group()` and `console.groupEnd()`  which the default notifier of this library uses. 

Now of course this library allows you you to pass in a `notifier` options to handle it yourself, but it has quite a fair amount of data returned to you which can be overwhelming initially for you to figure out what is going on. [I have created a gist](https://gist.github.com/Genhain/19a90a43882302691e6123fcce7c562e) which i hope has similar behaviour to the default console. Some feedback/corrections would be appreciated as i think this is a fantastic tool but anyone using a similar stack to me might not find it easy to use.

Another thing  i have noticed is that `React.memo()` seems to suppress why did you render logs but was supposed to be fixed in `v3.3.4` as the closing comment in #50 says

**Comment by vzaidman** [comment]
you can use the "onlyLogs: true" option as shown in
https://github.com/welldone-software/why-did-you-render#options
you can even pass custom
```
    consoleLog,
    consoleGroup,
    consoleGroupEnd,
```
functions (although it's not documented.)

**Comment by vzaidman** [comment]
regarding React.memo,
please take a look at the tests of React.memo scenarios

https://github.com/welldone-software/why-did-you-render/blob/master/src/patches/patchMemoComponent.test.js

do you think the library misses anything?

**Comment by vzaidman** [comment]
please reopen if you have any new questions.
