### ISSUE TITLE
[feature request] Can track why `useEffect()` triggered due to which deps changed ?

### ISSUE THREAD

**Issue by grepug** [welldone-software/why-did-you-render#67]
same as `useMemo()`, `useCallback()`

**Comment by vzaidman** [comment]
we have this feature I think. but it only tracks if a useEffect is changed "without a good reason" e.g: 
```
useEffect(() => {

}, [a]);
```
where old a is = {b: 'b'}
new a is = {b: 'b'}

where these are depp equals different objects:
old a !== new a

**Comment by vzaidman** [comment]
try `Component.whyDidYouRender = {logOnDifferentValues: true}`

**Comment by grepug** [comment]
I wonder if you can help me with this:

I have a component `A`. inside it there is a big object wrapped by `useMemo()` with several deps, something like 
```js
const A = () => {}
const obj = useMemo(() => { ... something big }, [a, b, c, d, e]);
```

**Comment by grepug** [comment]
I wonder if you can help me with this:

```js
const A = () => {
   const obj = useMemo(() => ({
     // something big
  }), [a, b, c, d, e])
}
```
and the `obj` is passed to a child component. And WDYR warns me that component `A` rerendered because of hook changes. 

so I am confused that if `obj` changed, it will only cause the child component to rerender, not the component `A` itself.

**Comment by vzaidman** [comment]
you are right. the message is wrong in this case. it's a bug what you see. i'll fix it soon.

it confuses a render of A because of useState with useMemo

```
const A = () => {
   const [state, setState] = useState(false);

 return <button onClick={currentState => setState(!currentState)} />;
}
```

**Comment by vzaidman** [comment]
opened a bug about the wrong message #68

**Comment by vzaidman** [comment]
made sure useMemo no longer triggers a why did you render console
