### ISSUE TITLE
wrong message when useMemo re-renders

### ISSUE THREAD

**Issue by vzaidman** [welldone-software/why-did-you-render#68]
In the following case:
```
const A = () => {
   const obj = useMemo(() => ({
     // something big
  }), [a, b, c, d, e]);

 return <Child  obj={obj} />;
}
```
when the hook `useMemo` re-creates obj even if it's deps deep equals, the message says A was re-rendered because if it, where in reality useMemo re-generated `obj` without a reason, but A is not re-rendered because of this.

**Comment by vzaidman** [comment]
removed useMemo from being concidered as a reason for re-renders

**Comment by vzaidman** [comment]
are you using the latest version?

**Comment by vzaidman** [comment]
@Hypnosphi hey!
do you remember why we did this?
Who do we even care if useMemo/useCallback returns a deep equals result?

**Comment by code-guru** [comment]
I use v4.3.2, the useMemo is used inside own custom hook, and the custom hook is not tracked by wdyr.

**Comment by Hypnosphi** [comment]
@vzaidman because we will most likely pass it as a prop after all

**Comment by Hypnosphi** [comment]
But I agree that those shouldn't be considered reasons for rerender of the component that uses them. I think we can only update `dependenciesMap` in them, without tracking hook changes

**Comment by Hypnosphi** [comment]
To be fair, `useMemo` already was there at the moment of https://github.com/welldone-software/why-did-you-render/pull/147/files

**Comment by vzaidman** [comment]
OK! I just wanted to make sure.

**Comment by vzaidman** [comment]
@Hypnosphi now i also see that
```
dependenciesMap.set(hookResult, get(args, dependenciesPath))
```
saves the deps of the hook per hook result.

but if a hook simply returns an object that was created anywhere else it might create false positives.

for this reason I will only keep useCallback and remove useMemo from participating in `dependenciesMap`.

it's rare to return functions from useMemo anyway...

**Comment by Hypnosphi** [comment]
not so rare:

```js
const throttledCallback = useMemo(() => throttle(callback, timeout), [callback, timeout])
```

**Comment by Hypnosphi** [comment]
Also, `dependenciesMap` can't create false positives, only false negatives: it marks some functions as deeply different

**Comment by vzaidman** [comment]
gotcha i'll keep it inside.

By the way the throttle example is an anti pattern based on React docs:
> You may rely on useMemo as a performance optimization, not as a semantic guarantee. In the future, React may choose to “forget” some previously memoized values and recalculate them on next render, e.g. to free memory for offscreen components. Write your code so that it still works without useMemo — and then add it to optimize performance.

**Comment by Hypnosphi** [comment]
What is the recommended way to do that?

**Comment by vzaidman** [comment]
i think
```
const [throttledCallback] = useState(() => throttle(callback, timeout))
```

**Comment by vzaidman** [comment]
check out https://twitter.com/0xca0a/status/1314326386555924480

**Comment by Hypnosphi** [comment]
What if both `callback` and `timeout` are dynamic?

**Comment by vzaidman** [comment]
Probably a longer and uglier hook using useRef...

**Comment by vzaidman** [comment]
this guy built a whole library around it:
https://github.com/alexreardon/use-memo-one

**Comment by vzaidman** [comment]
i'll release version 5 very soon.
