### ISSUE TITLE
WhyDidYouRender changes behaviour of my component

### ISSUE THREAD

**Issue by ZackTherrien** [welldone-software/why-did-you-render#69]
How does the flag `static whyDidYouRender = true/false;` change components? 

When I remove the flag from my component, my component unmounts, then remounts after each update.

However as soon as I add the flag (whether true or false), and change nothing else, the component no longer mounts/unmounts.

How does the this flag/library affect component lifecycle methods?

**Comment by vzaidman** [comment]
can you please add some information?
It sounds like you have some bug that's not related to the library.

**Comment by vzaidman** [comment]
feel free to re-open with extra information

**Comment by ZackTherrien** [comment]
I do have a bug that is unrelated to the library. However I would expect this bug to still exist when using this library...
