### ISSUE TITLE
Warn on non-plain objects with same prototype and own fields

### ISSUE THREAD

**Issue by Hypnosphi** [welldone-software/why-did-you-render#74]
Right now there is a false negative with non-plain objects passed as props, e.g. errors:

```js
const DisplayError = memo(({error}) => (
  <>
    <h1>{error.message}</h1>
    <p>{error.stack}<p>
    {error instanceof SomeSpecificError && <SomethingElse />}
  </>
)

const App = () => {
  const [counter, increment] = useReducer(state => state + 1, 0)
  useEffect(() => setTimeout(increment, 100), [])
  return <DisplayError error={new Error('message')} />
}
```

here, `error` prop is deep equal to the previous value but there's no warning 

One possible solution is to check both `Object.getPrototypeOf(obj)` and `Object.keys(obj)` for non-plain objects

**Comment by VariableVasasMT** [comment]
Can I pick this up?

**Comment by vzaidman** [comment]
yes, go on :)

**Comment by vzaidman** [comment]
@VariableVasasMT no success? :)

**Comment by VariableVasasMT** [comment]
@vzaidman I am extremely sorry, shit hit the fan, will pick this up, this week.

**Comment by vzaidman** [comment]
what's up @VariableVasasMT?

**Comment by barakyosi** [comment]
@vzaidman @VariableVasasMT I saw this issue was stale for few months so I opened a PR for it, hope you don't mind.
LMKWYT :)

**Comment by vzaidman** [comment]
Great!
I'll go over the pr asap!
Thank you!
