### ISSUE TITLE
`TypeError: Cannot read property 'useMemo' of undefined`

### ISSUE THREAD

**Issue by lucypoly** [welldone-software/why-did-you-render#75]
I have **React 16.8**
After
```
import React from 'react';

if (process.env.NODE_ENV !== 'production') {
  const whyDidYouRender = require('@welldone-software/why-did-you-render');
  whyDidYouRender(React);
}
```

I received an error:
`TypeError: Cannot read property 'useMemo' of undefined`

**Comment by vzaidman** [comment]
give me a little information about your app.
Is this the entry file of the whole application?
maybe you need to move this code to index.js or something

**Comment by lucypoly** [comment]
Thanks, that helps. But I have 100+ components. Should I register them all
to check re-render?

вт, 19 нояб. 2019 г., 10:05 Vitali Zaidman <notifications@github.com>:

**Comment by lucypoly** [comment]
Your library already have helped a bit, Thanks)

вт, 19 нояб. 2019 г., 10:15 Vitali Zaidman <notifications@github.com>:

**Comment by vzaidman** [comment]
I'm really happy :)
