### ISSUE TITLE
Documentation: what to do when "different React elements with the same displayName."

### ISSUE THREAD

**Issue by xgc1986** [welldone-software/why-did-you-render#8]
I got the message "different React elements with the same displayName."

But i don't know what I have to do to fix that, I've been looking of how to fix that, but I had no luck with that

About the message is true, is trying to re-render a Element that has not changed, and I don't have a forceUpdate anywhere

**Comment by vzaidman** [comment]
this is a component:
```
function MyComponent(){
  
}
```
this is a react element:
```
const element = <MyComponent/>
```
and it is equivalent to
```
const element = React.createElement(MyComponent, {})
```
you probably pass `<SomeComponent/>` to a component that you expect wont re-render.
and it creates a new element each time, right?

**Comment by xgc1986** [comment]
exactly

**Comment by vzaidman** [comment]
so your component will re-render every time even if it's pure because
<SomeComponent/> !== <SomeComponent/>
an this is always true.

what you can do is to wrap the both of the components in a pure component
```
class TwoComponents extends React.PureComponent{
  render() {
     return (
        <ComponentA b={<ComponentB/>}/>     
      )
  }
}
```
and then both of them will only re-render if the props of `TwoComponents` changes

**Comment by xgc1986** [comment]
I already have all components extending PureComponent, that is why I don't understand why is this happening, also I have not implemented shouldComponentUpdate or anything like that.

```
interface Props {
    className ?: string;
    style?: React.CSSProperties;
    children?: React.ReactNode;
}

export default class Li extends React.PureComponent<Props> {

    render(): React.ReactNode {
        return (
            <li
                className={this.extendClassName()}
                children={this.props.children}
                style={this.props.style}
            />
        );
    }
}
```

**Comment by vzaidman** [comment]
what is passed to Li?

**Comment by xgc1986** [comment]
```
    <ul>
      <Li>
        <img/>
      </Li>
    </ul>
```
If had some custom element inside I would undertand why it is re-rendering, but I have an image, and on other Li only have plain text

**Comment by vzaidman** [comment]
Ok. so `<img/>` is a new react-element on every render.
This is why `Li` cant be pure.

**Comment by xgc1986** [comment]
yes `this.props.children !== nextProps.children`always returns true.

then, if a component of my mine has children, then, do the cannot be Pure?

**Comment by vzaidman** [comment]
yes. they children is always new so they will always re-render even if they are pure.

**Comment by vzaidman** [comment]
I'll add it to the guide

**Comment by xgc1986** [comment]
thank you.

I will have to organize better my components, to prevent unnecesary re-renderings

**Comment by vzaidman** [comment]
This library was design to catch these types of errors so I'm happy it helped you :)

**Comment by vzaidman** [comment]
updated http://bit.ly/wdyr02
