### ISSUE TITLE
trackExtraHooks missing from WhyDidYouRenderOptions

### ISSUE THREAD

**Issue by nirvdrum** [welldone-software/why-did-you-render#82]
It looks like the TypeScript definitions have fallen a bit behind. The `WhyDidYouRenderOptions` interface is missing the `trackExtraHooks` property.

**Comment by vzaidman** [comment]
thanks ill fix it in a few days

**Comment by vzaidman** [comment]
fixed in [v3.6.0](https://github.com/welldone-software/why-did-you-render/releases/tag/v3.6.0)

**Comment by nirvdrum** [comment]
Thanks!
