### ISSUE TITLE
Missing documentation for using the library with enzyme

### ISSUE THREAD

**Issue by dagoltz** [welldone-software/why-did-you-render#87]
[This article](https://medium.com/welldone-software/why-did-you-render-mr-big-pure-react-component-2a36dd86996f) says:

> Enforcing
If you are concerned about missing these console logs, you can also use this library in your tests. The library perfectly works with enzyme and react-test-renderer, and as mentioned above you can report to an object in your tests to ensure nothing was re-rendered.

But I can't find any documentation on how to set why-did-you-render during all of my tests.
Can you direct me to the relevant docs or add some?

**Comment by vzaidman** [comment]
I forgot altogether I planned to write about it indeed.
I'm not sure when I'll get to it though.
It would looks something like in the tests of the library itself:
https://github.com/welldone-software/why-did-you-render/blob/master/tests/hooks/useState.test.js
instead of printing to the console, you can output redundant re-renders to an object and then make assertions about it:
```
    updateInfos = []
    whyDidYouRender(React, {
      notifier: updateInfo => updateInfos.push(updateInfo)
    })
```
```
test('setState of different values', () => {
    const ComponentWithHooks = () => {
      const [currentState, setCurrentState] = React.useState({b: 'b'})

      React.useLayoutEffect(() => {
        setCurrentState({b: 'c'})
      }, [])

      return (
        <div>hi! {currentState.b}</div>
      )
    }

    ComponentWithHooks.whyDidYouRender = true

    rtl.render(
      <ComponentWithHooks/>
    )

    expect(updateInfos).toHaveLength(1)
    expect(updateInfos[0].reason).toEqual({
      propsDifferences: false,
      stateDifferences: false,
      hookDifferences: [
        {
          pathString: '.b',
          diffType: diffTypes.different,
          prevValue: 'b',
          nextValue: 'c'
        },
        {
          pathString: '',
          diffType: diffTypes.different,
          prevValue: {b: 'b'},
          nextValue: {b: 'c'}
        }
      ]
    })
  })
```

**Comment by vzaidman** [comment]
I think my example here is enough.
If anybody finds the need to write tests about re-renders, you are welcome to leave a comment here.
