### ISSUE TITLE
Exclude re-renderings due to different children

### ISSUE THREAD

**Issue by asliwinski** [welldone-software/why-did-you-render#88]
Children prop is a special case when doing a component by component analysis in that it refers to a rerendering of a different component from the one under analysis. It would be handy to be able to disable logging of such cases using a parameter.

![image](https://user-images.githubusercontent.com/14044823/73691200-e7beb180-469f-11ea-929f-585991e0bc87.png)

**Comment by vzaidman** [comment]
I'm considering it.
But, from my experience, passing children to pure components (making them re-render on each render of their parents) is a very widespread scenario.
why do you track this component in the first place?

**Comment by asliwinski** [comment]
First of all thank you for this amazing piece of software, which already helped me optimize a lot :)

I actually didn't track that component (I used `include: [/^.*$/], exclude: [/^Connect/]`). The project I'm working on is full of such inefficiencies and it's tedious to identify particular components which are responsible, so I first use this basic filter, excluding just redux connects, and then visually identify those that seem to appear most often on the list. The way I think of it is that if the component rerenders due to its children it's that children's props (in most cases) fault, so I should first focus on the "regular" props of the component I'm analyzing and then move on to that particular children component as the next subject.
The problem is that by using that filter I get a lot of results similar to the example in the image.
Let me know if there's perhaps a better way to approach this.

**Comment by vzaidman** [comment]
try using `trackAllPureComponents` like shown in the last article about the latest version:
https://medium.com/welldone-software/why-did-you-render-v4-released-48e0f0b99d4c

Small efficiencies are not the way to go.

Mark the components you care to not render as pure and the library would track only them.

**Comment by Slapbox** [comment]
@vzaidman it would be helpful to us to have an option to disable logging about re-renders due to `props.children` changing. 

Some people don't realize that children causes re-renders of PureComponents, but if you do realize that and you're trying to find the re-renders you can actually address, then being notified that something updated because `children` makes it tougher to find those actionable items.

**Comment by vzaidman** [comment]
> Some people don't realize that children causes re-renders of PureComponents, but if you do realize that and you're trying to find the re-renders you can actually address, then being notified that something updated because `children` makes it tougher to find those actionable items.

the library helps you realize exactly this.

if you have children passed to pure components either make the component not pure, or memoize the children prop.


there is a problem however in cases where the children prop is **actually different**.
i need to think about what to do in these cases
