### ISSUE TITLE
False Positive

### ISSUE THREAD

**Issue by Aequitas737** [welldone-software/why-did-you-render#9]
Getting warning:
"Re-rendered because the state object itself changed but it's values are all equal." "This usually means this component called setState when no changes in it's state actually occurred." "more info at http://bit.ly/wdyr02"
prev state: Object {}  !==  Object {} :next state

I added a console log of the props, and it can be seen that its only rendering once per prop change.

The component:

```
class MyComp extends PureComponent {
    static whyDidYouRender = true;

    render() {
        console.log('rerendered', this.props.downloadProgress);
        return (
            <View/>
        );
    }
}

const mapStateToProps = state => ({
    downloadProgress: getDownloadProgress(state),
});

export default connect(mapStateToProps)(MyComp);
```

Every time the prop changes causing a rerender I get the warning above that the warning is unnecessary, which is false.

It may also be worth noting that this component is opened/hosted via react-navigation.

**Comment by vzaidman** [comment]
it probably has to do with react-navigation indeed because i don't see any reason why it's state changes. you does't even use it.

just to make it clear, your component doesn't look like it re-renders with the same props, the state it warns about is the `this.state` of `SyncView`, not the redux state.

I didn't work with react native for a long time so i'm not sure I can help you by myself.

but lets try some things:
1. what version of react do you use?
2. what version of the library do you use?
3. can you try the same by changing props through a father and not redux?

also in your example you wrap `MyComp`. is it a typo? do you need to edit it to be `SyncView`?

**Comment by vzaidman** [comment]
@Aequitas737

**Comment by Aequitas737** [comment]
@vzaidman 
1. "react": "16.5.2",
2. "@welldone-software/why-did-you-render": "^2.5.2"
3. I couldn't try as it's no longer set up in the same way, but It's worked before. 
Yeah it was a typo

**Comment by vzaidman** [comment]
ok. so you can't reproduce it anymore?

**Comment by Aequitas737** [comment]
As in I don't have why-did-you-render set up anymore. I only added it temporarily to test several tools to help improve performance of the app.

**Comment by vzaidman** [comment]
ok thanks. if you wish to try again with me you are welcome to reopen the issue.

**Comment by parties** [comment]
@vzaidman 

I am seeing this issue myself when using `connect` in a simple Todo app.

(I think) I have made a working demo replicating this bug; it appears to be showing a false positive about a different state object for a component that doesn't use state at all.

Demo here: https://codesandbox.io/s/1j4qc

**Comment by vzaidman** [comment]
@parties I dont have it here where I updated react-redux and redux:
https://codesandbox.io/s/whydidyourender-false-positive-demo-pjkn7

These older versions didn't handle state changes as well as the last version.
I strongly suggest using the last one.

**Comment by parties** [comment]
I had those packages set to the older versions since those are the current versions of the application I'm currently working on (large app, not a trivial upgrade).

Thank you for taking a look, @vzaidman.

**Comment by dihan** [comment]
Updating Redux fixed this issue for me
