### ISSUE TITLE
Logs don't work on conditionally rendered components

### ISSUE THREAD

**Issue by rbrewington** [welldone-software/why-did-you-render#94]
I've installed and configured why-did-you-render as layed out in the README.

I'm getting logs on some components, but anything that is a child of a component like this cannot seem to be logged:
```jsx
ParentComponent = () => {
  return someBoolean ? <ComponentThatIWantLogsFor /> : null;
}
```
There's no error or anything; I just don't get any logs.

I tried to create a minimal reproduction, but I can't get the logs to work at all for some reason:
https://stackblitz.com/edit/why-did-you-render-issue94

**Comment by vzaidman** [comment]
you need to add `whyDidYouRender = true` to `ComponentThatIWantLogsFor`

or make it pure using `React.memo(function ComponentThatIWantLogsFor(){ ... }):
and use
```
  whyDidYouRender(React, {
    trackAllPureComponents: true,
  });
```

**Comment by rbrewington** [comment]
I had already added whyDidYouRender = true.
I'm not so familiar with React.memo, but won't it prevent re-renders?

**Comment by rbrewington** [comment]
I added a stackblitz. It demonstrates my use case, but isn't very useful as the logs don't work at all for some reason.

**Comment by vzaidman** [comment]
why did you render usually logs only re-renders of components that can be prevented like:
```
<Comp aa={{a: '1'}}/>
```
If you want to log every single render and what changed, use:
```
TestConditionalComponent.whyDidYouRender = {
  logOnDifferentValues: true,
};
```
