### ISSUE TITLE
Doesn't work: not showing anything (sandbox included)

### ISSUE THREAD

**Issue by OnkelTem** [welldone-software/why-did-you-render#96]
I don't get why it doens't work.

From the description it follows that it's gonna help me with investigating the reasons of renders. So I created a sample app with state variable and one evident rerender but never saw anything in the console. 

Then I added additional component (MyComp) with the problem as the one from the docs - style anonymous object - but it didn't work anyway.

The sanbox:
https://codesandbox.io/s/determined-maxwell-itt99

Open the console, see how both MyComp and MyCompChild get called for no reason with the same props. why-did-you-render keeps silent....

**Comment by vzaidman** [comment]
i fixed it for you
https://codesandbox.io/s/lucid-dew-qt0u1

**Comment by OnkelTem** [comment]
@vzaidman So basically you added the line `whyDidYouRender(React);` to the App.js, did you?
Could you please explain, who this is required and why running the same in the `index.js` didn't help?

**Comment by vzaidman** [comment]
Ok i didn't notice you did it on `index.js`.
the important part is to do:

```
MyCompChild.whyDidYouRender = true;
```

so the component would be tracked.

please read the readme

**Comment by OnkelTem** [comment]
@vzaidman Thank you very much, now I see how it works!

> the important part is to do:
> 
> ```
> MyCompChild.whyDidYouRender = true;
> ```
> 
> so the component would be tracked.

Yep, and at first I did it realy, but for the App component. Because I was expecting it to print **some information** in any case, no mater is it rendering or even re-rendering.

> please read the readme

Oh I really did it. Thoroughly. And that README is the real source of the problem. Specifically, [this](https://github.com/welldone-software/why-did-you-render#usage) cleary states:

> Besides tracking **all pure components** using the `trackAllPureComponents` option, you can manually track any component you want by setting `whyDidYouRender` on them like this:
> `static whyDidYouRender = true`
> And for functional components:
> `BigListPureComponent.whyDidYouRender = true`

See? _Besides tracking **all pure components**_. Which *implies* that when one uses that option, then *ALL* the components must be tracked automatically, - and that never happens. And only when one needs to track some *specific* component then they 
a) skip the `trackAllPureComponents` option and 
b) set the component`s `whyDidYouRender` property to **true**.

**Comment by vzaidman** [comment]
Take a look now. Is it more clear?
I added an explanation of what exactly "pure components" mean and that "pure components" are not just any react components.

**Comment by OnkelTem** [comment]
> Take a look now. Is it more clear?
> I added an explanation of what exactly "pure components" mean and that "pure components" are not just any react components.

Oh yeah, now it's more clear of course. Because our `MyComp` is a pure component indeed. Now it's ok, thank you very much for this update Vitali.

Here is update sandbox with classes:
https://codesandbox.io/s/ecstatic-mountain-6f902
Works as expected now.
