### ISSUE TITLE
Support for apollo/react-hooks`

### ISSUE THREAD

**Issue by BradyDavis-Shellz** [welldone-software/why-did-you-render#98]
I'm running into an issue when trying to use `trackExtraHooks: [[ApolloHooks, 'useQuery']]` where using `@apollo/react-hooks`. 

Running this crashes the application and gives me the error `TypeError: Cannot set property useQuery of #<Object> which has only a getter`.

Possibly related to [this issue.](https://github.com/welldone-software/why-did-you-render/issues/95)

**Comment by vzaidman** [comment]
the issue is discussed at #85 with a workaround

**Comment by tpict** [comment]
I'm not certain that the workaround in #85 is applicable to this library as it doesn't ship with a UMD version :(
