### ISSUE TITLE
Add an option to report why did the owner render

### ISSUE THREAD

**Issue by Hypnosphi** [welldone-software/why-did-you-render#99]
I use WDYR extensively, and I find myself doing the following quite often:

— See a re-render warning about `MyComponent` with "This could have been avoided <...> by preventing its father from re-rendering"
—  Find this particular usage of `MyComponent`, and identify its owner ("father"): `OwnerComponent`
— Re-run WDYR, this time with `{include: [/^MyComponent$/, /^OwnerComponent$/], logOnDifferentValues: true}`, to find out which particular (maybe useful) re-render of `OwnerComponent` caused the useless re-render of `MyComponent`

It would be nice If I could see the reason of owner's re-render right away. If such a feature is welcome, I'll be happy to send a PR

**Comment by vzaidman** [comment]
I usually use the "rendered-by" feature of dev tools for this. Isn't it enough?
How do you suggest detecting why the "father" component rendered? to achieve this, we need to probably add tracking to all the fathers of all tracked components as well i think.

**Comment by Hypnosphi** [comment]
> I usually use the "rendered-by" feature of dev tools for this.

It doesn't show the relevant change in owner's props

> to achieve this, we need to probably add tracking to all the fathers of all tracked components as well i think

Yes, probably. That's why I suggest making it an option

**Comment by vzaidman** [comment]
and how do you suggest this information to be shown to the users?

**Comment by Hypnosphi** [comment]
Something like this:

```
v MyComponent 
    > {MyComponent: f} "Re-rendered because of props changes:"
  >  props.foo
  v Rendered by: OwnerComponent
      > {OwnerComponent: f} "Re-rendered because of props changes:"
    >  props.bar
```

**Comment by vzaidman** [comment]
sure let's give it a try. sounds great

**Comment by Hypnosphi** [comment]
> we need to probably add tracking to all the fathers of all tracked components as well

Ok looks like it's not achievable without adding tracking to all the components, because a component can become other component's owner at any point in runtime. So I think I'll just add "Rendered by", without the reasons

**Comment by vzaidman** [comment]
we are not looking at components per se. we are looking at instances of components.
so you can track the component's props as well as it's father's props. no?

**Comment by Hypnosphi** [comment]
> it's father's props

Also, hooks & state. I'll try

**Comment by vzaidman** [comment]
implemented!
